### ISSUE TITLE
I cannot find the solver.prototxt .

### ISSUE THREAD

**Issue by JackMicheal** [lmb-freiburg/flownet2#101]
Then set up your network for training ($net is a folder in models):

$ cd /path/to/$net 

$ cp ../solver_S_<type>.prototxt solver.prototxt 

$ cp $net_train.prototxt.template train.prototxt 

#Edit train.prototxt and make sure all settings are correct

$ caffe train --solver solver.prototxt 

Where is the solver.prototxt?

**Comment by nikolausmayer** [comment]
in `/models` after using the download script archive. There are three `solver_S_XXX.prototxt` files. Choose the one for the schedule you want to train.

**Comment by JackMicheal** [comment]
Thanks!I found it.
