### ISSUE TITLE
About the compiling process?

### ISSUE THREAD

**Issue by WANGYuSCU** [lmb-freiburg/flownet2#104]
Inside the directory, under ubuntu I have done these steps.
1. cp Makefile.config.example Makefile.config
2. revise the Makefile.config:  CPU ONLY, python sitepackage which include numpy, /usr/include/hdf5/serial, /usr/lib/x86_64-linux-gnu/hdf5/serial;
3. make -j 5 all tools pycaffe

This compiling process will aways fail.
I am the first time to use ubuntu and make. Could some one give me advice on how to run it on my computer? Thanks.

**Comment by nikolausmayer** [comment]
Hi,
the FlowNet2 does not work with CPU_ONLY. You have to enable GPU support to compile and use our codebase. This is because we do not have CPU code for some of our custom layers.

**Comment by WANGYuSCU** [comment]
Thanks a lot.
By the way, Is GTX-980 enough then?
If it is not enought, I will give up. Or I will run them in my desktop.
Thank again.

**Comment by nikolausmayer** [comment]
Yes, a GTX 980 can run all our networks.
If compilation causes more problems, you can also check out our FlowNet2 Docker image: https://github.com/lmb-freiburg/flownet2-docker
It's the same code, but you only have to install docker and nvidia-docker manually.

**Comment by WANGYuSCU** [comment]
Thank you!
And sorry to bother you again. I am not familiar with ubuntu and make.
So which option is right. 
(1) should I compile caffe inside BVLC/caffe first. And then inside flownet2 and excute "make -j 5 all tools pycaffe"
(2) Just inside flownet2 and excute "make -j 5 all tools pycaffe".
I am confused. I succeed in compiling caffe inside BVLC/caffe. I mean using "make all" "make test" "make run test".
With the same config setting, there are errors in compiling in flownet2.

Sorry, maybe I can't understand your first 2 steps. And it takes me much time to install cuda8.0 and cudnn5.1 on my ubuntu.

**Comment by WANGYuSCU** [comment]
Sorry to bother you again.
In compiling I can't understand.
In BVLC/caffe, I can compile with "make all" "make pycaffe" with success.
But inside the flownnet2, why there are always errors and I can't succeed with "make -j 5 all tools pycaffe". Errors are:
Makefile:576: recipe for target '.build_release/src/caffe/layers/imgreader_layer.o' failed

**Comment by WANGYuSCU** [comment]
Could I ask one more question?
I think preparation work is enough. 
However while I am running the demo script, I got message as bellow.

WARNING: Logging before InitGoogleLogging() is written to STDERR
F0209 16:59:25.602334 26357 layer_factory.cpp:69] Layer conv1 has unknown engine.
*** Check failure stack trace: ***
Aborted (core dumped)

I checked relative information saying to change engine from cuda to caffe. But how, which file and which sentence. I am really confused.

**Comment by nikolausmayer** [comment]
The proposed change should be in the `deploy.prototxt` file of the network you are running. Look for "engine: cudnn" lines.
I've never seen that error myself. Maybe it's caused by another Cuda or CuDNN installation?

**Comment by WANGYuSCU** [comment]
Thanks  I find it in the last.
Still new problem comes, I am a beginner of Ubuntu.
I really brought you so much trouble.

**Comment by WANGYuSCU** [comment]
So what is your cuda and cudnn version.
I am using cuda8.0 and cudnn5.1. Enen I changed the engine to caffe.
Problem "Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file" shows. 
TAT

**Comment by nikolausmayer** [comment]
Hm.. are you perhaps in a wrong directory? Or do you have multiple version of Protobuf installed which might interfere which each other?

**Comment by WANGYuSCU** [comment]
Thank you. I have succeed in running your code.
I didn't check the result yet. But indeed there is a .flo file generated.
I found many of the problem is because of makefile.config, cuda and cudnn installation. 
It is really painful to know which one to set. I have referenced many documents and found it out finally.

**Comment by WANGYuSCU** [comment]
I have one more question.
After the generation of the .flo file. I find with readflow function provided in your code is not working in windows. But on my macbook, I can read the optical flow data successfully.
I wonder is that the .flo file better been processed in ubuntu?

**Comment by nikolausmayer** [comment]
Yes, I know... the system setup is a pain.

The .flo problem might be something about the line endings in the file; they are by convention different in windows and linux. I don't use macOS but I would guess it follows the linux format.

**Comment by WANGYuSCU** [comment]
Really thanks a lot for your help.
