### ISSUE TITLE
Augmenting during test

### ISSUE THREAD

**Issue by adizhol** [lmb-freiburg/flownet2#106]
Hi,

Thank you for publishing the code and weights.
I have a small question - why is it necessary to augment input images when evaluating on test (production) images?

Thanks!

**Comment by nikolausmayer** [comment]
Hi,
we are using the "augmentation" layer in test mode, but only for mean subtraction. It was just convenient for us to not switch to another layer for that.
No geometry or color augmentation is done in production.

**Comment by adizhol** [comment]
Ok, thx
