### ISSUE TITLE
running flownet2 error

### ISSUE THREAD

**Issue by msiraj83** [lmb-freiburg/flownet2#107]
Hello I download the code and build. I have installed two caffe. First I  remove the path for the first version and set the paths to this version..the screen shot of the paths is given..
![flownet2_path](https://user-images.githubusercontent.com/8863047/36197029-32117272-11a5-11e8-9670-cd766d167fcb.png)
Second:- i try to run the code first i got this error...
![flownet2_login_error](https://user-images.githubusercontent.com/8863047/36197108-726f18e2-11a5-11e8-8192-21f03f3e2e7e.png)
Third:- I open run-flownet.py file and comment the two line (Line no 61 and 62) and the try to run the code. Again i got the following error.

![flownet2_ex_erro](https://user-images.githubusercontent.com/8863047/36197244-dd245aa8-11a5-11e8-8293-aa4ccf1535b9.png)

**Comment by nikolausmayer** [comment]
Hi,

that looks like there is something wrong with the paths. Python seems to find your other Caffe installation, and the libcaffe that is loaded is not the right one either (it's built with another caffe.proto file).

- Does "echo $LD_LIBRARY_PATH" produce the same output as "sudo echo $LD_LIBRARY_PATH"?

- What does Python print for `print(caffe.__file__)`?

**Comment by msiraj83** [comment]
Dear @nikolausmayer 

Thanks for your reply. 

- Library path with `sudo` and `with out sudo`
![ld_path](https://user-images.githubusercontent.com/8863047/36247940-5d772b46-1268-11e8-86ec-d973f01c8156.png)


- Output of `print(caffe.__file__)`
![caffe_path](https://user-images.githubusercontent.com/8863047/36247871-1d121e58-1268-11e8-9560-e93f72907e9b.png)

**Comment by nikolausmayer** [comment]
Hm. That's the correct folder at least, and that module does contain `set_logging_disabled`.  What's the output of `sudo python -c "import caffe; print(caffe.__file__)"`?

There has to be a path problem *some*where.

**Comment by msiraj83** [comment]
Dear @nikolausmayer 
The output of `sudo python -c "import caffe; print(caffe.__file__)"`?

![paython_package_path](https://user-images.githubusercontent.com/8863047/36260754-ee6c1aea-1294-11e8-8dc1-d869f0d07849.png)

**Comment by nikolausmayer** [comment]
Aha! So running the FlowNet script as `sudo` loads another Caffe package. So your `$PYTHONPATH` might be different for `sudo`.

**Comment by msiraj83** [comment]
Dear @nikolausmayer 

Thanks for your reply and help. I am new to ubuntu.. Can you tell me how to set caffe path for `sudo` commond. I try to set the path in .bashrc and .profile file in PATH variable as well create CAFFE_PATH variable but still its not working. 

Thanks

**Comment by nikolausmayer** [comment]
When you are using `sudo`, you normal `.bashrc` (which is `$HOME/.bashrc`, for you perhaps `/home/msiraj83/.bashrc`) is not used. Instead, the shell tries to use `/root/.bashrc`. You can try copying your config files to `/root` and see if that helps.
However, I think the better option is to **not use `sudo`**. Nothing about our scripts should require more than user permissions. Do you get an error if you omit `sudo`?

**Comment by msiraj83** [comment]
Yes, I copy .basrhc file to /root/ and run the following code with out sudo..
`siraj@siraj-System-Product-Name:~/Programs/flownet2-master/scripts$ ./run-flownet.py ../models/FlowNet2-s/FlowNet2-s_weights.caffemodel ../models/FlowNet2-s/FlowNet2-s_deploy.prototxt ../examples/images/cat.jpg ../examples/images/cat_gray.jpg z.flo` 
I got the following error..
![without_sudo](https://user-images.githubusercontent.com/8863047/36372807-bf45ee42-1598-11e8-8622-c6c661cca672.png)
 And when I run with sudo than i got the followoing error.
![with_sudo](https://user-images.githubusercontent.com/8863047/36372859-f461fb02-1598-11e8-9125-bbca88ef0fc7.png)
It mean still not get the right path for caffe..??

**Comment by nikolausmayer** [comment]
The version without `sudo` looks better. The "unknown engine" error might be a CuDNN problem. Check out issue https://github.com/lmb-freiburg/flownet2/issues/104, maybe this helps you (or ask Google about "engine: CUDNN").

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
