### ISSUE TITLE
Did you use all of Things3D for finetune?

### ISSUE THREAD

**Issue by chuchienshu** [lmb-freiburg/flownet2#109]
Hi @nikolausmayer , I know you train the flownet2 on chairs frist, and then fine-tuning on Things3D. I want to know if you have used all the data sets? I mean all of the right, left, into_future and into_past, or you just used part of it? Thanks a lot!

**Comment by nikolausmayer** [comment]
Hi,
we used all of right/left and into_future/into_past. However, we excluded samples with extreme values which are not very helpful for disparity or optical flow estimation. I'm working on a definite list of samples we used; it'll be available on our dataset download page when it's done.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)

**Comment by texastone** [comment]
Has this list been published? I did not see it from the latest distribution.
