### ISSUE TITLE
Why multiply flow ground truth by 0.05?

### ISSUE THREAD

**Issue by dsqx71** [lmb-freiburg/flownet2#11]
I was wondering why you multiply ground truth by 0.05. It seems to influence actual learning rate.

**Comment by eddy-ilg** [comment]
It is not equivalent to modifying the learning rate. The reason we did it is to have image and flow values normalized to a range of approximately -0.5 to 0.5. It seems that it is not absolutely necessary though.

**Comment by dsqx71** [comment]
Thanks for your reponse. I got your point.
