### ISSUE TITLE
HDF5 library version mismatched error

### ISSUE THREAD

**Issue by haoliyoupai09** [lmb-freiburg/flownet2#114]
I try to implement the flownet in matlab. 
First I compile the matcaffe successfully, then I utilize the trained model weight and network deploy like this:
osvos_params.caffe_path = '/media/atr/0000678400004823/flownet/matlab/';
osvos_params.useGPU =1;
osvos_params.gpu_id = 0;
addpath(osvos_params.caffe_path);
caffe.reset_all();
osvos_params.test_model = fullfile('/media/atr/0000678400004823/flownet/models/FlowNet2','deploy.prototxt');
osvos_params.test_weights = fullfile('/media/atr/0000678400004823/flownet/models/FlowNet2','FlowNet2_weights.caffemodel.h5');
osvos_params.test_net = caffe.Net(osvos_params.test_model, osvos_params.test_weights, 'test');

when we run the last code, we get the hdf5 mismatch error. The HDF5 header files used to compile this application do not match the version used by the HDF5 library to which this application is linked.
Headers are 1.8.11, library is 1.8.6. I find that the hdf 1.8.11 is linked to our setting in makefile.config when compiling caffe. But I could find where the hdf1.8.6 comes, do you have any ideas? Any help is appreciated. And we do not use annconda and the hdf5 linked to annoconda is 1.8.18.

**Comment by nikolausmayer** [comment]
I don't know much about Matlab; is it possible that the 1.8.6 version is something from within Matlab?

**Comment by haoliyoupai09** [comment]
Thanks. We do find the hdf5 1.8.6 is correlated to matlab. And we think that the conflict error is also related to the caffemodel you provided in format (.caffemodel.h5). Maybe it is in conflict with the data format in matlab. We tried to replace the model in .caffemodel format in other files you provided (FlowNet2-C), and the  error disappeared. Have you ever saved the FlowNet2 in .caffemodel format? Could you send me a copy via email? Looking forward to your reply.

**Comment by nikolausmayer** [comment]
We don't have other formats for the snapshot files at the moment, sorry. However, conversion seems to not be too difficult, so I'd suggest you try that first: https://stackoverflow.com/questions/38038933/how-to-convert-hdf5-format-to-caffemodel-format-in-caffe/38046872#38046872

**Comment by haoliyoupai09** [comment]
Okay, we will try this. Thank you very much.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
