### ISSUE TITLE
Problem regarding dataset

### ISSUE THREAD

**Issue by qewtqwqqq** [lmb-freiburg/flownet2#115]
Hi
I am training Dispnet model on the kitti dataset, I don't know where I did this wrong.
I load the ground truth disparity image, and do the conversion in python:
pfm=np.float32(image/np.float32(256.0))
and use the pfm file produced(I use the readPFM and writePFM function in python), and make the lmdb database.

After I train the model, I test it, and I found the float numbers in result are far different from the ground truth, all range in (0,1), although if I use the command line(cvkit tools provided by kitti):
sv result.pfm:
to visualize the pfm as images, it looks kind of like the ground truth.
So where did I do this wrong?

**Comment by nikolausmayer** [comment]
Does the groundtruth image after `pfm=np.float32(image/np.float32(256.0))` look right? Did you read the KITTI groundtruth using KITTI code?
If the test results "look" right, they might just be wrongly scaled. If so, I'd suspect the scaling error to happen before training :thinking:

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
