### ISSUE TITLE
Making Caffe and Flownet is Completed but cannot run run-flownet.py

### ISSUE THREAD

**Issue by PouriaCh** [lmb-freiburg/flownet2#116]
I have set everything up and make process for Caffe and Flownet main folder is done but when I want to run "run-flownet.py", it gives me this error: 

Traceback (most recent call last):
  File "./run-flownet.py", line 24, in <module>
    if(not os.path.exists(args.deployproto)): raise BaseException('deploy-proto does not exist: '+args.deployproto)
BaseException: deploy-proto does not exist:  /home/pouria_chalangari/Desktop/flownet2-master/models/FlowNet2/FlowNet2_deploy.prototxt.template

#####################################
I am sure I am giving the correct location of deploy.prototxt file and the filename is correct too.

My OS is UBUNTU 16.04 and my GPU is NVIDIA K80. I installed CUDNN 5.1 and CUDA 8.0. 
Could you please help me with this?

**Comment by nikolausmayer** [comment]
What's the full command line that produced this error?

Could it be a permissions issue? Are you able to read the file yourself?

Does `python -c "import os; print os.stat('/home/pouria_chalangari/Desktop/flownet2-master/models/FlowNet2/FlowNet2_deploy.prototxt.template')"` print an error?

**Comment by PouriaCh** [comment]
I used this command:

`./run-flownet.py /home/pouria_chalangari/Desktop/flownet2-master/models/FlowNet2/FlowNet2_weights.caffemodel.h5 \ /home/pouria_chalangari/Desktop/flownet2-master/models/FlowNet2/FlowNet2_deploy.prototxt.template \ /home/pouria_chalangari/Desktop/flownet2-master/data/FlyingChairs_examples/0000001-img0.ppm /home/pouria_chalangari/Desktop/flownet2-master/data/FlyingChairs_examples/0000001-img1.ppm /home/pouria_chalangari/Desktop/test1.flo`

My computer just has one user. I don't think it's because of permission. What file you are referring to? 
I may have used symbolic paths during setting up my system. Not sure.

That python command does not give me an error. This is the result of that line:

`posix.stat_result(st_mode=33188, st_ino=3852576, st_dev=2049, st_nlink=1, st_uid=1002, st_gid=1003, st_size=62798, st_atime=1522289156, st_mtime=1522289156, st_ctime=1522289156)`

**Comment by nikolausmayer** [comment]
Hm, I really don't know what might be the problem. [Others suggest](https://stackoverflow.com/questions/3112546/os-path-exists-lies) it might be an NFS issue. In any case, I don't think it's related to our code, but rather to something in your local setup...

**Comment by PouriaCh** [comment]
Thank you for your time.

**Comment by PouriaCh** [comment]
Is there sth else that I might have forgotten during system setup or package installations? Any idea?

**Comment by nikolausmayer** [comment]
I currently cannot think of another angle. The script seems to fail before the Caffe stuff even starts, so it's hard to judge whether something might have gone wrong there :) and it fails on a basic builtin operation, so I doubt this has anything to do with particularities of our code. You already said that there is only one user on the workstation, and I don't see why the file in question should belong to `root`.

**Comment by PouriaCh** [comment]
I was told using new versions of CUDA and CUDNN would cause Flownet2 fail running. Is that true? Could you please let me know of a suitable setting for drivers and packages which work flawlessly with Flownet2?

**Comment by nikolausmayer** [comment]
Our Docker package works on:
- NVidia driver 384.59 (passthrough from host with a GTX 970)
- CUDA v8.0.61
- CuDNN v5.1.10
so this should be a reliable configuration.

**Comment by PouriaCh** [comment]
Thanks. Hope I can get it work

**Comment by PouriaCh** [comment]
I started to redo everything from scratch and I got to the point to install CUDNN. For cudnn-dev using .deb file, it asks me to do update-alternative. I looked for it and people suggest to do this linking chain:
`/usr/include/cudnn.h -> /etc/alternatives/libcudnn -> /usr/include/x86_64-linux-gnu/cudnn_v5.h`

Could you please let me know the exact commands for this, cause I'm new with this and afraid to mess this up.

**Comment by nikolausmayer** [comment]
(I'll have say upfront that I've never done this.)

1. check that `/usr/include/x86_64-linux-gnu/cudnn_v5.h` exists
2. `sudo ln -s /usr/include/x86_64-linux-gnu/cudnn_v5.h /etc/alternatives/libcudnn`
(now check (`ls -l /etc/alternatives/libcudnn`)that the link exists and points to `/usr/include/x86_64-linux-gnu/cudnn_v5.h`)
3. `sudo ln -s /etc/alternatives/libcudnn /usr/include/cudnn.h`
(now check that this new link exists)

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
