### ISSUE TITLE
Run in real time with web cam

### ISSUE THREAD

**Issue by mazisound** [lmb-freiburg/flownet2#117]
Hi,
I saw your videos on youtube and I want to try running the code in real time using a web cam. Could you please help me with?
Maziar

**Comment by nikolausmayer** [comment]
Hi,
sorry, but we don't have public code for that. I suggest you start from the `run-flownet-many.py` script and combine it with OpenCV code (to get webcam images and to display results). The flow color conversion for display is adapted from http://vision.middlebury.edu/flow/code/flow-code.zip

**Comment by mazisound** [comment]
Thank you very much Nikolaus.
