### ISSUE TITLE
Directory structure for training. 

### ISSUE THREAD

**Issue by TusharNimbhorkar** [lmb-freiburg/flownet2#119]
Hi

I want to train flownet2 on a different dataset.
What should be the directory structure for the data directory(images, flows)?

Thanks

**Comment by nikolausmayer** [comment]
The directory structure does not matter, what matters is that the list file is formatted correctly. Take a look at https://github.com/lmb-freiburg/flownet2/blob/master/data/FlyingChairs_release.list, the format is "first-image second-image flow", and each line is one data sample

**Comment by TusharNimbhorkar** [comment]
So
`convert_imageset_and_flow.cpp` created two files `data.mdb` and `lock.mdb`

Now in order to train the model. I need to edit `train.prototxt` 

1.From what I got I need to change `data_param{source: "path/of/the/files/mentioned/above"}` ?
2. Also, I do not have any test data at the moment. So  I leave the source for the test as empty?

**Comment by nikolausmayer** [comment]
1. Yes, that'll be your LMDB file
2. You need test data, but for debugging you can just reuse the training data here. You might need to copy the database file in case only one concurrent reader is allowed (not sure, I don't use LMDB).

**Comment by TusharNimbhorkar** [comment]
seems to be working. 

Thanks for the help. :)

Closing the issue.
