### ISSUE TITLE
Deploy template 

### ISSUE THREAD

**Issue by TusharNimbhorkar** [lmb-freiburg/flownet2#121]
Hi

I trained the flownet model with different dataset. How do I generate $net_deploy.prototxt.template ?

**Comment by nikolausmayer** [comment]
You don't need a new template file if you only changed the training dataset (without changing the architecture).

**Comment by nikolausmayer** [comment]
Yes.

**Comment by TusharNimbhorkar** [comment]
Yup, it works. Thanks again

Closing the issue.
