### ISSUE TITLE
how to change the batch size when testing

### ISSUE THREAD

**Issue by jeremy43** [lmb-freiburg/flownet2#123]
Hi, when I try to run run-flownet-many, the batch size is one pair img (img0, img1,.flo), and took about 1s per pair. Ss there any way to change to batch size when testing? Thanks!

**Comment by nikolausmayer** [comment]
The input blobs are assembled [here](https://github.com/lmb-freiburg/flownet2/blob/master/scripts/run-flownet-many.py#L45). You can change that code to stack multiple image pairs into one batch. Note that you'll also need to change the [output code](https://github.com/lmb-freiburg/flownet2/blob/master/scripts/run-flownet-many.py#L112) accordingly.

If you are concerned about speed, you might want to try what https://github.com/lmb-freiburg/flownet2/issues/105 suggested first.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
