### ISSUE TITLE
regarding padding and stride in 1d correlation

### ISSUE THREAD

**Issue by stalin18** [lmb-freiburg/flownet2#125]
Hi, first of all thanks for sharing this great work! I was porting you 1D correlation API in TensorFlow and I've several doubts in the code:

1. I am wondering why pad size is not equal to max_displacement (in the code, padded width = 2*pad_size)? 
int paddedbottomwidth = bottom[0]->width()+2*pad_size_;

In the paper, it is written that a displacement of 40 is used with stride2 = 1, therefore, isn't padding = 40 required? What pad size do you supply?

2. single_direction variable: I hope the value -1 corresponds to the case of estimating disparity for left image and +1 corresponds to the case of estimating disparity for right image.

Thank you in advance!

**Comment by nikolausmayer** [comment]
1. I'm not sure, but the factor 2 might be a remainder of a network version that didn't do _single_-direction correlation. In that case we'd pad both directions by max_displacement.
2. I hope so too. At least that's what it _should_ correspond to.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
