### ISSUE TITLE
Input preprocessing to use pretrained weights

### ISSUE THREAD

**Issue by CarolusM** [lmb-freiburg/flownet2#128]
I have the network running with its pretrained weights but I was wondering whether I should normalize the input images in the range (0,1) or in the range (-1,1). As far as I know, I need to normalize the input images in the same range that it was done while training the weights provided.

Any help would be highly appreciated. Thanks in advance!

**Comment by nikolausmayer** [comment]
The input range is (0,255) per channel. The network's first few layers do the necessary normalization.

**Comment by CarolusM** [comment]
Ok, thank you for your reply!

Even if I only use FlownetSimple (as in here [https://arxiv.org/pdf/1504.06852.pdf](url) ) instead of FlowNetCorr the input should be in that range?

**Comment by CarolusM** [comment]
Perfect. I am using the FlowNetS weights of this repository. I am using it for a different purpose (not opticalflow) in which I am using as input two stacked images and I was wondering if these images should be normalized.

In your first reply, you said that the first few layers do the necessary normalization. Is this only that way when using the entire FlowNet2? Or if I use only FlowNetS it is the same?

Thanks again in advance!

**Comment by nikolausmayer** [comment]
All the FlowNet2-??? variants include this. What I don't know is whether the original codebase for FlowNet1 does it as well, but it'll be fine if you use the FlowNet2-S from this repo.

**Comment by xuezhisd** [comment]
* the original image ranges [0,255], it will scale to [0,1] firstly, and do other augmentation according the network config file.
* the augmentation of flownet and flownet2 is very similar. But if you want to train a stereo network, the augmentaion should not include rotation etc.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
