### ISSUE TITLE
About training "FlowNet2-SD" on ChairsSDHom dataset

### ISSUE THREAD

**Issue by zmlshiwo** [lmb-freiburg/flownet2#130]
Hi, 
I am training the model "FlowNet2-SD" on ChairsSDHom dataset with "long" schedule, but the loss seems too large. The total loss 4000 to 7000. Is this phenomenon normal?  When I was training "FlowNetS" , the total loss is about 30~150.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
