### ISSUE TITLE
Some question about retraining the DispNet on my own dataset

### ISSUE THREAD

**Issue by ZoyeJay** [lmb-freiburg/flownet2#131]
Hi.
the image pairs in my dataset are gray scale with only one channel, all the groundtruth is pfm,  the training set is about 1900 image pairs, and now I want to retrain the dispnet by this dataset, Could you please tell me how can I modify the network structure for training. thanks a lot.

**Comment by nikolausmayer** [comment]
I wouldn't change the network structure at all. For starters, I would just make a dumb grayscale→color converter which clones the single image channel into dummy RGB channels. Then you effectively have a color dataset and you can use the network as is.

If that works out well and you think that limiting the network to 2x1 input channels could improve results, then you probably have to work on the augmentation code. I don't think it'll work on single channels in its current form.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
