### ISSUE TITLE
min and max values

### ISSUE THREAD

**Issue by hassanzaal** [lmb-freiburg/flownet2#133]
I want to convert the resulted optical flow to another range. Could I know the typical min and max values?

**Comment by nikolausmayer** [comment]
The flow min/max are a function of your data, not the network. I don't know your data, so I have no idea what your flow range is ;)

For our datasets, there are no defined min/max values. If you want to normalize the range, just choose some threshold and clip outliers...

**Comment by hassanzaal** [comment]
Thank you.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
