### ISSUE TITLE
run-flownet-many.py gives error:"F0517 19:16:30.993336 15835 layer_factory.cpp:69] Layer conv1 has unknown engine."

### ISSUE THREAD

**Issue by wangwen39** [lmb-freiburg/flownet2#134]
Does anyone else have met this error? I try to use Flownet2 to get flow of many pair images. I just run the script run-flownet-many.py ./model_path ./deploy_path ./txt_path 
Thanks for helping me!

**Comment by SaiK95** [comment]
Was there ever a solution to this?

**Comment by nikolausmayer** [comment]
@SaiK95 I don't know the origin of this error, but others have reported that a simple fix works for them: https://github.com/bqlabs/flownet/issues/1#issuecomment-221827895

**Comment by BasicCoder** [comment]
you need open USE_CUDNN := 1 switch in Makefile.config
