### ISSUE TITLE
Slow download speed

### ISSUE THREAD

**Issue by tn00364361** [lmb-freiburg/flownet2#135]
Hi. I tried to download the dataset with the script `data/download.sh` but it was extremely slow. The speed was kept at <100KB/s. Is there any way to make it faster?

**Comment by nikolausmayer** [comment]
Sorry, but we don't have mirrors for our downloads :-/  where are you located?

**Comment by tn00364361** [comment]
I am downloading from a university network in Michigan, USA. Somehow the speed went up to ~3 MB/s now...

**Comment by nikolausmayer** [comment]
Were you able to finish the downloads?

**Comment by tn00364361** [comment]
Yes. The largest file was the zip for optical flow, which took me ~30 hours to download.

**Comment by nikolausmayer** [comment]
Ok :)

**Comment by feipan664** [comment]
It's still too slow to download for me. Located in Daejeon, Korea, the speed is about 30KB/s~ Any possibility to share on Google Drive or any other approachable way?

**Comment by nikolausmayer** [comment]
@feipan664 you can try these torrents; you might be lucky and get another seeder with a better uplink to you:
http://academictorrents.com/details/20afbe18b5d1754b75deeefe4c2c74b17c9ea792
http://academictorrents.com/details/93a54256fe2f56dea2c7d247af11d9affa06a06d

(they are legit; I made them and we also seed them).

**Comment by feipan664** [comment]
@nikolausmayer  Very much thansk!
