### ISSUE TITLE
Does the pretrained-model which downloaded is support for other dataset? such as face expression dataset optical flow?

### ISSUE THREAD

**Issue by sharpstill** [lmb-freiburg/flownet2#136]
I am doing research of face expression recognition.  I use download.sh to download your model. 

I am wondering `FlowNet2-C_deploy.prototxt.template` `FlowNet2-C_weights.caffemodel` does it can support face images??? 

What is the dataset do you train?

**Comment by nikolausmayer** [comment]
`FlowNet2-C` is trained on [FlyingThings3D](https://lmb.informatik.uni-freiburg.de/resources/datasets/SceneFlowDatasets.en.html). For other FlowNets we additionally used [ChairsSDHom](https://lmb.informatik.uni-freiburg.de/resources/datasets/FlyingChairs.en.html#chairssdhom).

The network is a general-purpose optical flow network, so yes, you can use if for facial images.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
