### ISSUE TITLE
Data augmentation?

### ISSUE THREAD

**Issue by buemi** [lmb-freiburg/flownet2#139]
Hi,
in the paper describing the FlowNet training process is described the "online" data augmentation step, crucial to reduce overfitting risks.
Is not obvious for me, wher this step is  implemented in the scripts for the models training is performed. Can you explain, please?

**Comment by nikolausmayer** [comment]
Our augmentation is "online" as in "it happens within the network while it is training". It is implemented as dedicated layers within the network itself, not the wrapper scripts. Look for layers whose name contains "augmentation".

**Comment by buemi** [comment]
Now it is clear, thank you.
