### ISSUE TITLE
Purpose of setting black border in BlackAugmentationLayer

### ISSUE THREAD

**Issue by wang-yijie** [lmb-freiburg/flownet2#140]
Hi,
BlackAugmentationLayer randomly sets corresponding borders of image and flow to zero. What is the purpose of this augmentation?
In testing, input images are resized to the desired shape, containing no black borders. Why black borders are added during training?

**Comment by nikolausmayer** [comment]
Hi,

some

**Comment by nikolausmayer** [comment]
Hi,

the black border is a type of augmentation. We use it to teach the network how to deal with images that have, well, black borders ;)
The small-displacements network tends to treat image borders like this wrongly, so we teach it explicitly.

**Comment by wang-yijie** [comment]
Thx!
