### ISSUE TITLE
importError: failed to import enum_type_wrapper

### ISSUE THREAD

**Issue by buemi** [lmb-freiburg/flownet2#142]
Hi,
I receive the following error when I execute the run-flownet script:

_flownet2/python/caffe/proto/caffe_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named google.protobuf.internal_

Any idea?

**Comment by nikolausmayer** [comment]
Try installing `libprotobuf-dev`, `protobuf-compiler` and `python-protobuf` if they are not already installed.

**Comment by buemi** [comment]
Yes, all the packages are installed, but the error persists.

**Comment by nikolausmayer** [comment]
Ok, those packages are installed, then your `$PYTHONPATH` might not include the path to the module.
- What does `locate google/protobuf/internal/__init__` print? 
- What does `echo $PYTHONPATH` print?

**Comment by buemi** [comment]
It's quite strange:

_$ echo $PYTHONPATH
/home/buemi/home/buemi/Antonio/flownet2/python/caffe/python:/usr/local/lib/python2.7/dist-packages/pip:_

There is a double home location in the path! Which is the script where I have to look in order to correct it?

**Comment by nikolausmayer** [comment]
Hm, there is this line in `set-env.sh`:
```CAFFE_PATH="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"```

Maybe this is misbehaving?

**Comment by buemi** [comment]
But what is the correct caffe path? I found several "caffe" folders:

- flownet2/.build_release/python/caffe (empty)
- flownet2/.build_release/python/caffe (empty)
- flownet2/src/caffe
- flownet2/python/caffe

but noone has a subfolder named "python"

**Comment by nikolausmayer** [comment]
It should be `flownet2/python`. The `caffe` within that folder is the module loaded by `import caffe` in Python.

**Comment by buemi** [comment]
"import caffe" provides the original error:
_>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/buemi/Antonio/flownet2/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver
  File "/home/buemi/Antonio/flownet2/python/caffe/pycaffe.py", line 15, in <module>
    import caffe.io
  File "/home/buemi/Antonio/flownet2/python/caffe/io.py", line 8, in <module>
    from caffe.proto import caffe_pb2
  File "/home/buemi/Antonio/flownet2/python/caffe/proto/caffe_pb2.py", line 6, in <module>
    from google.protobuf.internal import enum_type_wrapper
ImportError: No module named google.protobuf.internal_

Have I to set the protobuf path somewhere?

**Comment by nikolausmayer** [comment]
Depends — what is the location of your protobuf (`locate google/protobuf/internal/__init__`)?

**Comment by buemi** [comment]
It seems to be here:
/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/__init__.py
/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/__init__.pyc

**Comment by nikolausmayer** [comment]
I see. Well, since your `$PYTHONPATH` only contains `/usr/local/lib/python2.7/dist-packages/pip`, I'd try adding `/usr/local/lib/python2.7/dist-packages` to it ;)

**Comment by buemi** [comment]
It seems I solved by installing protobuf locally. Thanx

**Comment by nikolausmayer** [comment]
Fair enough :grin:
