### ISSUE TITLE
Fine tuning on sintel

### ISSUE THREAD

**Issue by TusharNimbhorkar** [lmb-freiburg/flownet2#144]
Hi

Do you make any changes to train.prototxt while finetuning on sintel.
Like batch size or crop ratio. And the number of iterations in solver.prototxt.

**Comment by nikolausmayer** [comment]
Sintel finetuning cropsize is 768x320. 
Depending on the dataset, pretraining used 768x384 (FlyingThings3D) or 448x320 (FlyingChairs and other small datasets).
No change to batchsize.
The iteration number follows the S_file schedule.

**Comment by TusharNimbhorkar** [comment]
Hey @nikolausmayer 

Thanks for the Answer.

But I am still not sure about the weights inside Flownet2-S, Flownet2-C, Flownet-c. Are only trained on flying chairs. Because I tested average epe on this models with the sintel validation you just said in above answer and cross checked with table 2 from [here](https://arxiv.org/pdf/1801.06397.pdf). And It doesnt match. 

Can you confirm this or who should i contact to get more info. 

Thanks again

**Comment by nikolausmayer** [comment]
The numbers in the paper you referenced are not representative. Numbers within that table are only for comparison within that same table (not necessarily comparable to other experiments or even other papers), and the network weights are not the ones published with the FlowNet2 paper.

The data that I have says that FlowNet2-C and FlowNet2-S were trained on FlyingChairs, but I wasn't a part of the FlowNet1 team. Eddy Ilg from our lab is your best contact option in this matter.

FlowNet2-c from the FlowNet2 CVPR paper (Ilg et al.) is trained differently from the FlowNet2-c instance which we trained for the later IJCV paper (Mayer et al.). The former is trained on a Chairs→Things3D schedule, the latter on many different things depending on the specific experiment.

**Comment by nikolausmayer** [comment]
(closed due to inactivity, but feel free to reply if the issue persists)
