### ISSUE TITLE
FlowNet-C training curve

### ISSUE THREAD

**Issue by texastone** [lmb-freiburg/flownet2#145]
I am training C using FC dataset and the long schedule, all default parameters. The flow_loss2 output is flat at 5000 from very early stage to about iteration 650000 and then starts to drop and kind of appearing normal. I was wondering if this is an expected behavior. Should I try different hyper-parameters?
It seems github does not have an option to let me upload image.

**Comment by tonmoy-saikia** [comment]
Typically it drops sharply in the beginning. After 100k you should see some results which already makes sense.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
