### ISSUE TITLE
capture image after augmentation give black image

### ISSUE THREAD

**Issue by alhersh** [lmb-freiburg/flownet2#146]
Hello,

I am trying to capture the images after performing augmentation, but the images that I capture are all black! I have used the ImgWriter to capture them. 

Any suggestion?

thanks.

**Comment by nikolausmayer** [comment]
The input data is normalized to a [0,1] range (using `Eltwise` layers) before the augmentation layers. If you do not undo this scaling, your images are likely just far too dark :slightly_smiling_face:

**Comment by alhersh** [comment]
Just now, I have removed the `Eltwise`  layers before the augmentation and still I am getting black images!

**Comment by nikolausmayer** [comment]
I don't think removing the pre-augmentation `Eltwise` layers will work. The augmentation layers expect the [0,1] data range and probably don't know how to deal with other data.
The normalization is likely not really *necessary* for the network (meaning that you could retrain without it and it would still work), but our nets have been trained with it... so now they need the normalization at test time, too :slightly_smiling_face: 
I suggest adding another `Eltwise` layer between the augmentation and your `ImgWriter`, to "denormalized" the augmented data. The new layer should just multiply everything with 255.

**Comment by nikolausmayer** [comment]
I *think* doing the scaling in the ImgWriter layer should work, too. Perhaps there's a different in how edge cases are treated, but it sounds like it should do the same.

If the augmentation layer includes this scaling, then I think you don't have to do any other scaline.

We tried to strike a balance between "larger crops → better" and "smaller crops → more possible different training samples".

**Comment by alhersh** [comment]
Many thanks for your patience Nikolaus in replying all my questions and for all the clarifications.
