### ISSUE TITLE
Eltwise1 and 2 SUM or PROD

### ISSUE THREAD

**Issue by pedropgusmao** [lmb-freiburg/flownet2#148]
Hello, 
I am trying to replicate the results for FlowNetS with Tensorflow starting from the train.prototxt.
I am a bit puzzled about the Eltwise1 layer that has an operation SUM with coeff 0.00392156862745, which looks a lot like 1/255. 
Shouldn’t this operation be PROD instead of SUM? The same goes to Eltwise2 layer. 

Thanks in advance

**Comment by nikolausmayer** [comment]
The convention can be confusing, but `SUM` is correct here:
The `PROD` operation in `Eltwise` does elementwise multiplication of 2 bottom blobs. The `SUM` op linearly scales a bottom blob by the `SUM` coefficient.

**Comment by pedropgusmao** [comment]
Thanks!
