### ISSUE TITLE
Message type "caffe.LayerParameter" has no field named "black_augmentation_param"

### ISSUE THREAD

**Issue by yxqlwl** [lmb-freiburg/flownet2#15]
Hi, 
     Sorry for troubling. Errors occurred in the training process:
     1. "Message type "caffe.LayerParameter" has no field named "black_augmentation_param""
     I cannot find the definition of black_augmentation in src/caffe/layers or caffe.proto. I am wondering if I missed something?
    2. Unknown bottom blob 'img0_a_org' (layer 'crop_params')
Thanks~

**Comment by brjeon** [comment]
I believe img0_a_org stands for the original Image 1.
Therefore, I have changed some names in the train.prototxt as following.
blob0 -> img0_a_org
blob1 -> img1_a_org
blob2 -> flow_gt_a_org
Correct me if I am wrong.

However, I still cannot  figure out what img0_b, img1_b, flow_gt_b stand for.

**Comment by yxqlwl** [comment]
Thanks. I also think so. I will check it.

**Comment by nikolausmayer** [comment]
Hi yxqlwl,
I cannot find any mention of a black_augmentation_param in the codebase. I'm assuming that the error occurs in a layer you added?

**Comment by brjeon** [comment]
Hi nikolausmayer,
For your information the 'black_augmentation_param' is mentioned in
'FlowNet2-CSS-ft-sd_train.prototxt.template'.

**Comment by yxqlwl** [comment]
Hi nikolausmayer,
    As brjeon mentioned, it is found in 'FlowNet2-CSS-ft-sd_train.prototxt.template'. May be there are different versions of the code? :)

**Comment by brjeon** [comment]
Actually, the above mentioned 'FlowNet2-CSS-ft-sd_train.prototxt.template' file is not in the githb codebase.
It is created after running 'download-models.sh' file which is located in the 'flownet2-master/models' directory.

**Comment by nikolausmayer** [comment]
Woops sorry, now I see. I didn't check the models. We'll look into what's missing.

**Comment by yxqlwl** [comment]
Thanks~

**Comment by eddy-ilg** [comment]
Thanks for pointing this out, the code part it missing in the repo. I will add it during the week.

**Comment by eddy-ilg** [comment]
Black augmentation layer is now in the repo.

**Comment by yxqlwl** [comment]
Thank you!
