### ISSUE TITLE
Why the flow data is divided by 32 here and then multiplied by 32 in the data layer

### ISSUE THREAD

**Issue by gyguo** [lmb-freiburg/flownet2#151]
https://github.com/lmb-freiburg/flownet2/blob/9eed763789c06fa5f44e7af79078c0446a82bfc6/tools/convert_imageset_and_flow.cpp#L176

**Comment by nikolausmayer** [comment]
This is a remnant from our in-house database format and its compression ("multply floats by 32 and store them as 16-bit integers"). It's in the code release to keep the training setting close to what we used, but you can remove this from the conversion tool and the data layer if you want. As far as we know, this has no functional value or relevance.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
