### ISSUE TITLE
How to set correlation_param?

### ISSUE THREAD

**Issue by lawpdas** [lmb-freiburg/flownet2#155]
Hi ! I want to use the correlation layer to do cross-correlation between two feature maps. But I don't know how to set the correlation_param ?  What is the meaning of stride in blob1/2 ?

**Comment by nikolausmayer** [comment]
```
optional uint32 pad = 2 [default = 0]; // The padding size (equal in Y, X)
optional uint32 kernel_size = 3; // The kernel size (square)
optional uint32 max_displacement = 4; // The maximum displacement (square)
optional uint32 stride_1 = 5 [default = 1]; // The stride in blob 1 (equal in Y, X)
optional uint32 stride_2 = 6 [default = 1]; // The stride in blob 2 (equal in Y, X)
```

Padding and kernel size are as in a convolutional layer.
The maximum displacement limits how far away correlation will be done (more -> larger displacements can be correlated, but also more computation).

`stride_1` is the stride in the first bottom blob (the one for which you want to compute correlation), `stride_2` in the second bottom blob (the one to which you want to correlate entries from the first bottom blob). 
Example: `stride_1 = 2; stride_2 = 1`, only every 2nd pixel will get correlation data, but all those pixels get fully dense correlation. If `stride_1 = 1; stride_2 = 2` is 2, every pixel will get correlation data, but that data will be sparse. 

See also [in the code](https://github.com/lmb-freiburg/flownet2/blob/master/src/caffe/layers/correlation_layer.cu#L81).

**Comment by nikolausmayer** [comment]
Perhaps there is a misunderstanding about the purpose of the correlation layer.
Your example uses the 2nd bottom blob as a filter.

The intended use of the correlation layer is to correlate position P in the 1st bottom blob with a neighborhood around P in the 2nd bottom blob. Both bottom blobs must have the same dimensions (see [here](https://github.com/lmb-freiburg/flownet2/blob/master/src/caffe/layers/correlation_layer.cpp#L46).

`blob2` _is not a filter input_. You input two images and the output is a bunch of local correlation scores between pixel positions on those two images. You can very much compare what the correlation layer does with what a disparity estimation algorithm does when it compiles a cost volume over multiple possible displacements per pixel.

**Comment by lawpdas** [comment]
Yes, I completely misunderstood the purpose of the correlation layer. Thank you！
