### ISSUE TITLE
Flying Things 3D dataset is not publicly available?

### ISSUE THREAD

**Issue by yasunorikudo** [lmb-freiburg/flownet2#157]
Hi.

First of all thank you for your great work!

I'm currently reproducing FlowNet2.0 and had one question.
Flying Things 3D dataset for training is not publicly available?

**Comment by yasunorikudo** [comment]
Oh, I found a download script.
https://github.com/lmb-freiburg/flownet2/blob/master/data/download.sh
I'm sorry for confusing.

**Comment by nikolausmayer** [comment]
That download script only gets the data related to optical flow. If you want more, check out https://lmb.informatik.uni-freiburg.de/resources/datasets/SceneFlowDatasets.en.html
