### ISSUE TITLE
Prepare kitti flow files for online evaluation

### ISSUE THREAD

**Issue by alhersh** [lmb-freiburg/flownet2#158]
Hi,

I have used FlowNet2 to produce .flo files. Since two months, I am trying to submit the results as kitti explains: " Optical flow maps are saved as 3-channel uint16 PNG images: The first channel
contains the u-component, the second channel the v-component and the third
channel denotes if the pixel is valid or not (1 if true, 0 otherwise)". But I can't!

My question is: how I can convert the generated optical flow from FlowNet to be in the specified PNG format? Since the generated optical flow has only 2 channels? From your experience, what is valid pixel or not?

One of the ways I have tried is adding another dimension to the flo file will all ones! 
 
Many thanks,

Taha

**Comment by nikolausmayer** [comment]
- go to http://www.cvlibs.net/datasets/kitti/eval_scene_flow.php?benchmark=flow,  search page for "download development kit" and download it
- look for file `io_flow.h` which can write KITTI-format PNG files
- go to http://vision.middlebury.edu/flow/submit/, search for "flow-code" and download it
- look for file `flowIO.h` which can read FLO files

That gives you all the code you need to convert FLO files into the PNG format expected by KITTI, you just need to cobble it together yourself.

**Comment by Thomas-Mccabe** [comment]
Hi, 

Alhersh, I have ran into the same issue. Have you had any luck solving this?

Thank you,
Tom
