### ISSUE TITLE
Run flownet2 in windows

### ISSUE THREAD

**Issue by mmohamed2222** [lmb-freiburg/flownet2#159]
Hi,
please how i can run it in windows x64 ?
Thanks

**Comment by nikolausmayer** [comment]
We do not support Windows.

FlowNet2 is based on Caffe which has a Windows version -- but we do not know whether our old Caffe code is compatible with it. You are on your own here :slightly_smiling_face:

**Comment by mmohamed2222** [comment]
Thank you for your answer
