### ISSUE TITLE
Trouble installing and running flownet2.

### ISSUE THREAD

**Issue by TomerFw** [lmb-freiburg/flownet2#161]
Hello,
I have been trying to install flownet2 for a few days now and I'm having troubles with it.
Could you please write the list of dependencies needed to install and run it properly?
I'm trying to install it on ubuntu 16.04 on an anaconda environment that has python3 installed on it.
Currently receiving an error concerning protobuf version.

Thanks in advance.

**Comment by nikolausmayer** [comment]
(depending on your usecase, our [Docker variant](https://github.com/lmb-freiburg/flownet2-docker) might be easier to use)


Besides CUDA and CuDNN (v5), the dependencies for Python 2 should be (via our [Dockerfile](https://github.com/lmb-freiburg/flownet2-docker/blob/master/Dockerfile#L19)):

`module-init-tools build-essential ca-certificates libatlas-base-dev libboost-all-dev libgflags-dev libgoogle-glog-dev libhdf5-serial-dev libleveldb-dev liblmdb-dev libopencv-dev libprotobuf-dev libsnappy-dev protobuf-compiler python-dev python-numpy python-scipy python-protobuf python-pillow python-skimage`

Most Python 3 package variants should be easy to infer from this list, but I'm not sure about stock versions of Protobuf. We always compile that from source. 

If you install all the dependencies from packages, you should be able to use the [Makefile.config from the Docker repo](https://github.com/lmb-freiburg/flownet2-docker/blob/master/FN2_Makefile.config).

**Comment by TomerFw** [comment]
Thanks for the swift reply!
I tried running it with the docker and I get the following error:

et2 -v data/0000000-imgL.png data/0000001-imgL.png flow.flo
Using GPU:       0
Running network: FlowNet2
Working dir:     /flownet2/flownet2/scripts
First input:     data/0000000-imgL.png
Second input:    data/0000001-imgL.png
Output:          flow.flo
/flownet2/flownet2/scripts
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0904 14:30:49.677175    12 cudnn_conv_layer.cpp:52] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
/bin/bash: line 1:    12 Aborted                 (core dumped) python run-flownet-docker.py --gpu 0 /flownet2/flownet2/models/FlowNet2/FlowNet2_weights.caffemodel* /flownet2/flownet2/models/FlowNet2/FlowNet2_deploy.prototxt.template data/0000000-imgL.png data/0000001-imgL.png flow.flo

**Comment by nikolausmayer** [comment]
What GPU do you have in your system? For the "FlowNet2" model and the example images, there should be at least 4 GB free.
If you have multiple GPUs, you can use the `-g` parameter to choose one.

If you are unsure, you can post the output of `nvidia-smi`.
