### ISSUE TITLE
How to get the optical flow value in .flow file?

### ISSUE THREAD

**Issue by liangxi627** [lmb-freiburg/flownet2#163]
I have generated the .flo files of my dataset through the pre-trained model. How to get the value (u,v) in the .flo file at pixel location (x,y) in the original frame? Please help me~

**Comment by nikolausmayer** [comment]
C++: `flowIO` in http://vision.middlebury.edu/flow/code/flow-code/
Python: https://github.com/lmb-freiburg/flownet2/blob/master/scripts/run-flownet.py#L100-L115

The Python code produces NumPy arrays, that should be the easiest option.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
