### ISSUE TITLE
Is the default flownet2 only trained on FlyingThings3D?

### ISSUE THREAD

**Issue by achalddave** [lmb-freiburg/flownet2#166]
I'm pretty sure this is the case, but there doesn't seem to be a specific documentation.

The [`download_models.sh`](https://github.com/lmb-freiburg/flownet2/blob/9eed763789c06fa5f44e7af79078c0446a82bfc6/models/download-models.sh) script downloads  a bunch of models. I believe the default `FlowNet2/FlowNet2_weights.caffemodel.h5` model is trained on FlyingThings3D only; is that correct?

**Comment by FUZhanhong** [comment]
hello sir,

what about DispNetCorr1D? trained on FlyingThings3D and finetuned with KITTI2015? the paper <A Large Dataset to Train Convolutional Networks or Disparity, Optical Flow, and Scene Flow Estimation> has mentioned the dataset FlyingChairs, if i pre-trained the net with FlyingChairs, can the result be better for outdoor scene?

another question: in another issue in programme "dispnet-flow-docker" which you have closed, you have  mentioned that finetuned with KITTI2015 training data with GT(200), so the net in DispNetCorr1D-K is the same with DispNetCorr1D, or cutted the test part?

Thanks in advance!

**Comment by nikolausmayer** [comment]
@FUZhanhong _DispNetCorr1D_ only uses FlyingThings3D. FlyingChairs is not a disparity dataset, so that probably won't get you very far. _DispNetCorr1D-K_ is just _DispNetCorr1D_ with additional finetuning on KITTI data. I don't understand your question about the "test part".
