### ISSUE TITLE
New layers

### ISSUE THREAD

**Issue by Ivamcoder** [lmb-freiburg/flownet2#168]
Hi, 
Thanks for your paper,
I want to add your network to another network,
Could I please ask the list of new layers you have defined in caffe for your network?

**Comment by BluebirdStory** [comment]
Hi, I think it is in the include group

**Comment by BluebirdStory** [comment]
I also want to know where is the new layer, to be specific, where is the correspond layer? Thank you soooo much, by the way, your paper is really brilliant, it works well.
