### ISSUE TITLE
model refers to paper

### ISSUE THREAD

**Issue by Ivamcoder** [lmb-freiburg/flownet2#170]
Hi,
Which model in models folder has highest accuracy which is the contribution of this paper?

**Comment by nikolausmayer** [comment]
FlowNet2 is the highest-accuracy general purpose model.
FlowNet2-Sintel is the highest-accuracy Sintel model.
FlowNet2-KITTI is the highest-accuracy KITTI model.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
