### ISSUE TITLE
About compiling on OS X

### ISSUE THREAD

**Issue by BluebirdStory** [lmb-freiburg/flownet2#175]
Hi, I am now compiling your version of caffe on OS X, and I encounter this issue that I can not figure out:
nvcc fatal   : GNU C/C++ compiler is no longer supported as a host compiler on Mac OS X.

for more details:
<img width="727" alt="2018-11-13 8 17 24" src="https://user-images.githubusercontent.com/33217105/48412990-36251f00-e781-11e8-9238-1e50aca8a3db.png">
many thanks

**Comment by BluebirdStory** [comment]
Or say your version of caffe just does not support compiling on OS X, thank you

**Comment by BluebirdStory** [comment]
Right by the way, I am compiling your version of caffe on OS X 10.12.3, and in a conda virtual environment. The conda version is 4.3.27

**Comment by nikolausmayer** [comment]
We do not support OS X builds, sorry. I guess you could try CLANG or whatever host compiler NVCC supports on OS X, but that might just bring in its own host of problems.
You might be able to run [FlowNet2 in Docker](https://github.com/lmb-freiburg/flownet2-docker) — if OS X supports GPU passthrough (which I do not know)

**Comment by BluebirdStory** [comment]
All right, I guess it explains everything, but thank you anyway, appreciate for your contribution!
