### ISSUE TITLE
About compiling in a conda virtual environment on linux

### ISSUE THREAD

**Issue by BluebirdStory** [lmb-freiburg/flownet2#176]
I am now compiling your version of caffe on linux in a conda virtual env, and I keep on meeting this problem 
<img width="799" alt="2018-11-17 11 08 01" src="https://user-images.githubusercontent.com/33217105/48655929-19c30400-ea59-11e8-8055-eb0d72e1e6d8.png">
would you like to provide me with some advices? many thanks

**Comment by BluebirdStory** [comment]
I have successfully compile your version of caffe in the default environment, i.e. not the conda virtual env. I don't understand why every time I switch to the conda env, the CUDNN will go wrong. Do I need to install an independent CUDA and CUDNN in the virtual env?

**Comment by nikolausmayer** [comment]
This error occurs if you have CuDNN > 5. You can switch to CuDNN 5, but it's easy to fix the code your self: in `include/caffe/util/cudnn.h`, line 113 (check the documentation of CuDNN!) the function `cudnnSetConvolution2dDescriptor` now expects an additional argument (I think it's something like "datatype float"). Fixing that should make the CuDNN problem disappear. I've tested it with up to CuDNN 7.3 and I think this was the only necessary change.

**Comment by BluebirdStory** [comment]
Thank you sooooo much, you are my hero!!! @nikolausmayer
