### ISSUE TITLE
This is not actually an issue for this repository I'm sorry. But I'm wondering if you can help

### ISSUE THREAD

**Issue by AIaesthetic** [lmb-freiburg/flownet2#179]
I managed to create .flo list and I can visualize each .flo file thanks to http://vision.middlebury.edu/ . But I'm aiming to visualize the whole .flo list at once, not just each individual .flo file at a time. any help?
Thanks in advance

**Comment by nikolausmayer** [comment]
It sounds like that should be a simple case of "run the visualization app for every .flo file". What's your goal? A flow video?

**Comment by AIaesthetic** [comment]
It's a simple case. But, I have like a hundred .flo files. Won't be there a simpler way to do it? same as running Flownet2 on frames list? 
Yes, I'd like to make a video from the output .flo files.

**Comment by AIaesthetic** [comment]
it works. I love you
