### ISSUE TITLE
There is no issue with the code. I can run it perfectly and produce results. Just wanted to ask if there is a better way to visualize the network. Right now the pictures I get from draw net are very small and difficult to discern.

### ISSUE THREAD

**Issue by adhara123007** [lmb-freiburg/flownet2#184]
There is no issue with the code. I can run it perfectly and produce results. Just wanted to ask if there is a better way to visualize the network. Right now the pictures I get from draw net are very small and difficult to discern.

**Comment by nikolausmayer** [comment]
I don't have a better way to visualize the network :)  if you are not already using it, I suggest the `--rankdir TB` option; but it's still a massive image.

**Comment by adhara123007** [comment]
Thanks that helped !!
