### ISSUE TITLE
warp

### ISSUE THREAD

**Issue by zhuwanling** [lmb-freiburg/flownet2#186]
Is class Resample2d a warp operation class?

**Comment by nikolausmayer** [comment]
I am not sure what you mean by "warp operation". The `Resample2d` layer is a linear scaling operation, so I guess "yes", it is technically an edge case of image warping.

**Comment by zhuwanling** [comment]
# warp img1 to img0; magnitude of diff between img0 and and warped_img1, 
    resampled_img1 = self.resample1(x[:,3:,:,:], flownetc_flow)

Annotated warp  img1 to img0.
I understand that warp operation.

**Comment by zhuwanling** [comment]
Thank you for your reply
Warp operation,I think it is img1 to img2 by Optical flow diagram。
I don't find the code of warp operation, can you tell me.

**Comment by zhuwanling** [comment]
![8 aq_ ooq7 ck v tlszi](https://user-images.githubusercontent.com/25894416/53285400-e05a0d00-379a-11e9-8482-d7c8a6928ee8.png)

**Comment by zhuwanling** [comment]
![mmg22317 72cr q4s5](https://user-images.githubusercontent.com/25894416/53285408-126b6f00-379b-11e9-8e5b-d03b5afbd4ff.jpg)

**Comment by nikolausmayer** [comment]
Our warping layer implementation is in the `flow_warp_layer` files. `Resample2d` is _not_ a warping implementation in our code. It serves an entirely different purpose: forcing input dimensions to multiples of 64 during the deeper layers.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
