### ISSUE TITLE
Convert Imageset and flow option fail when used with -g flag

### ISSUE THREAD

**Issue by adhara123007** [lmb-freiburg/flownet2#187]
Hi, 

Can I use grayscale images to train the network ? also,
I used the ../build/tools/convert_imageset_and_flow.bin with -g flag to convert my grayscale images to lmdb format for training. But it fails with the following error :
+1: 
F0226 11:38:35.137490   296 convert_imageset_and_flow.cpp:350] Unknown db backend 0
*** Check failure stack trace: ***
    @     0x7f971922c5cd  google::LogMessage::Fail()
    @     0x7f971922e433  google::LogMessage::SendToLog()
    @     0x7f971922c15b  google::LogMessage::Flush()
    @     0x7f971922ee1e  google::LogMessageFatal::~LogMessageFatal()
    @           0x405cca  main
    @     0x7f97176b6830  __libc_start_main
    @           0x4066a9  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by nikolausmayer** [comment]
(Disclaimer: I did not write that code)
Argh. I think `convert_imageset_and_flow.bin` uses different parameters than documented in the file header (those are valid for `convert_imageset` from which this is derived). It looks like the valid parameters are:
`convert_imageset_and_flow LISTFILE DB_NAME RANDOM_SHUFFLE[0 or 1] DB_TYPE["leveldb" or "lmdb"]`

This tool might not be able to deal with grayscale images. In that case, you could reuse the code for that from `convert_imageset.cpp` or convert your grayscale images to "fake color" (=using all 3 RGB channels), e.g. using ImageMagick's `convert` tool:
`convert grayscale.png PNG24:actuallygrayscalebutpretendingtobecolor.png`
