### ISSUE TITLE
how to use driving dataset to train this network?

### ISSUE THREAD

**Issue by Lvhhhh** [lmb-freiburg/flownet2#19]
i have the dataset named driving including disparity and frames_cleanpass.  how can i use it to train the network? how can i transfer the pfm to flo? and how can i create the list ? does it work if i have the list ? what the list looks like? thank you!

**Comment by nikolausmayer** [comment]
Hi,

1. clone and compile this repo
2. follow the README to download the models (which include training prototxt files)
3. use [these scripts](https://github.com/lmb-freiburg/flownet2/issues/7) to convert PFM to FLO and generate `.list` files
4. use the `convert_imageset_and_disparity` tool (ships with this repo) to compile LMDB databases
5. adjust the train prototxt file for a network of your choice (in ./models) and train
6. ...
7. profit! ;)

Best,
 Nikolaus
