### ISSUE TITLE
Scripts that evaluating the model?

### ISSUE THREAD

**Issue by WormCoder** [lmb-freiburg/flownet2#195]
Thanks for sharing
I trained my custom model and I want to evaluate its performance like EPE.
Did you share you evaluation scripts?

**Comment by nikolausmayer** [comment]
No, but check out [KITTI's "development kit"](http://www.cvlibs.net/datasets/kitti/eval_scene_flow.php?benchmark=flow); it's all in there.

**Comment by WormCoder** [comment]
thanks a lot
