### ISSUE TITLE
Flownet2 outputs completely white flow

### ISSUE THREAD

**Issue by Cryptiex** [lmb-freiburg/flownet2#203]
I'm currently trying to evaluate the flow between an object in two different images. One image is the observed camera image and the other one a rendered version of the object using a colored 3D model.
A mask of the object is added to both the observed and rendered image to yield two images with four channels.

More specifically, I'm following the approach published by:
[https://github.com/liyi14/mx-DeepIM](url)

For some reason the output of the Flownet2 is completely blank. Does somebody know the reason for this behavior?

**Comment by nikolausmayer** [comment]
"Zero flow" may be caused by a subtly incompatible CUDA version. Please check if https://github.com/lmb-freiburg/flownet2/issues/201 works for you.

It might also be worth double-checking that you are not feeding the same image twice to FlowNet2 :wink:

**Comment by Cryptiex** [comment]
Thanks for the quick reply. I do not believe that this issue is based on the CUDA version since Flownet2 works for me on the ape model of the LINEMOOD6D dataset as shown here:

![ape_concat_4channels](https://user-images.githubusercontent.com/24294489/58234874-e894fa80-7d3f-11e9-92d7-faffaf6c3cef.png)

This is the output of the Flownet2 with my own 3D model. The object is centered and not in the upper right corner as the image may indicate:

![concat_4channels_DeepIM](https://user-images.githubusercontent.com/24294489/58234875-e894fa80-7d3f-11e9-88b4-763ef12f259b.png)

Is the Flownet2 robust against 3D models that do NOT perfectly match the object in the scene by color?

**Comment by nikolausmayer** [comment]
Ok, that's good. FlowNet2 is definitely robust against not _perfect_ color matches, but I never tried real vs rendered objects. Would it be possible for you to post an example image pair (or, if not, to send it to me via mail)?

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
