### ISSUE TITLE
diagonal filler in Flownet_S deploy

### ISSUE THREAD

**Issue by withinnoitatpmet** [lmb-freiburg/flownet2#208]
Hi, I am a little bit confused about the function of diagonal filler in last Conv Layer of flownet_s deploy prototxt. Could you please explain this for me? Thanks in advance. 
layer {
  name: "scale_conv1"
  type: "Convolution"
  bottom: "predict_flow_resize"
  top: "predict_flow_final"
  convolution_param {
    num_output: 2
    pad: 0
    kernel_size: 1
    stride: 1
    weight_filler {
      type: "diagonal"
      diag_val: $SCALE_WIDTH$
      diag_val: $SCALE_HEIGHT$
    }
    bias_filler {
      type: "constant"
    }
  }
}

**Comment by nikolausmayer** [comment]
That layer rescales the output flow.

The network needs input resolutions which are multiples of 64. Inputs that do not match this are rescaled to the next-higher fitting resolutions in X and Y independently. This means that the raw network output is a valid flow for the rescaled input, but not for the original input.

This final layer just rescales the raw network output by the X/Y factors which were introduced by the input upsampling.

**Comment by withinnoitatpmet** [comment]
> That layer rescales the output flow.
> 
> The network needs input resolutions which are multiples of 64. Inputs that do not match this are rescaled to the next-higher fitting resolutions in X and Y independently. This means that the raw network output is a valid flow for the rescaled input, but not for the original input.
> 
> This final layer just rescales the raw network output by the X/Y factors which were introduced by the input upsampling.

Thank you so much for your prompt reply!
