### ISSUE TITLE
One question about training on FlyingThings3D

### ISSUE THREAD

**Issue by yxqlwl** [lmb-freiburg/flownet2#21]

**Comment by yxqlwl** [comment]
Hi,
    When training on FlyingThings3D, should we use the flow files in folder .../into_future/left?

**Comment by nikolausmayer** [comment]
Hi,

the choices `into_future`/`into_past` and `left`/`right` should not matter in practice. There are no useful priors that distinguish any one from the others. 

We used `into_future/left`, but without a particular reason.

Best,
 Nikolaus

**Comment by yxqlwl** [comment]
Thank you!

**Comment by yxqlwl** [comment]
Hi,
     One more related question about this topic:
     In the things3D training set, I think:
     "optical_flow/TRAIN/A/0000/into_future/left/OpticalFlowIntoFuture_0007_L.pfm" corresponds to the following image pair:
     "frames_cleanpass/TRAIN/A/0000/left/0007.png"
     "frames_cleanpass/TRAIN/A/0000/left/0008.png"
      Is that correct?
Best
ViJay

**Comment by nikolausmayer** [comment]
exactly

**Comment by yxqlwl** [comment]
Thanks~
