### ISSUE TITLE
how to generate optial flow .flo and .rflo files?

### ISSUE THREAD

**Issue by aiwithshekhar** [lmb-freiburg/flownet2#218]
Can you please help me with the generation of .flo and .rflo files. I needed it for using in this repo https://github.com/lxx1991/VS-ReID. I am using windows 10 with nvidia quadro M2000, will i be able to run the makeFile if yes what are the changes required in makeFile.config.

**Comment by nikolausmayer** [comment]
I'm afraid we have no experience with Windows builds and cannot assist with this.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
