### ISSUE TITLE
Can we set this up on Google Colab?

### ISSUE THREAD

**Issue by JibKh** [lmb-freiburg/flownet2#220]
I am trying to set this up on Google Colab, however source set-env.sh line does not work since Google Colab does not allow virtual environments I believe. Continuing with the code leads to an error:
`
[libprotobuf ERROR google/protobuf/text_format.cc:298] Error parsing text-format caffe.NetParameter: 40:22: Message type "caffe.LayerParameter" has no field named "augmentation_param".
F0826 18:27:00.553436  6423 upgrade_proto.cpp:88] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /tmp/tmp3upr8ch4
*** Check failure stack trace: ***
`
Should I use the TensorFlow method instead of Caffe on Google Colab? https://github.com/sampepose/flownet2-tf

**Comment by nikolausmayer** [comment]
I have never used Colab, so I cannot give an authoritative answer, but I believe one cannot install arbitrary software there? In that case, our Caffe variant is ruled out anyway — it does not work with an off-the-shelf Caffe, you need our own code.

Using the TF implementation you linked is probably the better idea.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
