### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by yxqlwl** [lmb-freiburg/flownet2#23]
Hi, sorry for interrupting:

1. What is the usefulness of brightness error in FlowNet2? Is it used to indicate the location of false predictions?

2. After converting .pfm to .flo in the FlyingThings3D dataset, it seems that the flow files do not match the corresponding left images. For example:
https://cloud.githubusercontent.com/assets/24893551/26722513/a273554a-47d3-11e7-9c6e-6f01671f89d3.png
Maybe the flow data should be further processed or transformed( rotation, transpose, or scaled, etc. ) in the "pfm to flo" script?

Could you please provide some advice?  Thanks~

**Comment by xmfbit** [comment]
Looks like a horizontal flip can solve the second problem. But you should first check whether the visualization causes the problem, because the screen xy direction and matrix xy direction may not be the same,

**Comment by yxqlwl** [comment]
Hi xmfbit
    Thanks :). And I think it is not the problem of visualization because the display is correct for .flo files of FlyingChairs dataset.

**Comment by nikolausmayer** [comment]
Woops, @xmfbit is partially correct. The conversion script from the other issue does not take into account that the image rows are stored **bottom-to-top** in a PFM image.

Just flip vertically, that should do the trick!

Best,
 Nikolaus

**Comment by yxqlwl** [comment]
It works. Thank you~
