### ISSUE TITLE
how to show the .flo result?

### ISSUE THREAD

**Issue by xugangtongji** [lmb-freiburg/flownet2#24]
I have run **run-flownet.py** and get the .flo file. But i don't how to read the .flo and show it like the rgb image. Could anyone give me some advice?

**Comment by xmfbit** [comment]
You can refer to this: [readFlow in run-flownet.py](https://github.com/lmb-freiburg/flownet2/blob/master/scripts/run-flownet.py#L100-L115)

**Comment by nikolausmayer** [comment]
This should help: https://github.com/lmb-freiburg/flownet2-docker/issues/1
