### ISSUE TITLE
 two question

### ISSUE THREAD

**Issue by liu666666** [lmb-freiburg/flownet2#3]
Thanks for your nice work!
I have two questions:
1. I want to reconstruct the flying chairs dataset, could you please give me the code that generate the dataset？
2.could you please tell me how can i download the ChairsSDHom?

**Comment by nikolausmayer** [comment]
Hi liu666666,

1. I'm sorry, but the dataset generation assets and codebase contain code and data for which we do not have a redistribution license. We cannot legally release them.

2. We are currently preparing the download page. When it is done (within some days) you will find it here: https://lmb.informatik.uni-freiburg.de/resources/datasets/

Best,
 Nikolaus
