### ISSUE TITLE
Large transformations in data augmentation

### ISSUE THREAD

**Issue by sampepose** [lmb-freiburg/flownet2#30]
Hi there,

Thank you for your time with my previous questions. I attempted to rewrite the data augmentation code in TensorFlow.

Here are my original two images along with the corresponding flow:

| Image 0  | Image 1 | Flow |
| ------------- | ------------- | ------------- |
| ![img0](https://user-images.githubusercontent.com/1855931/27068453-33f01816-4fde-11e7-98e3-68b882bc265e.png)  | ![img1](https://user-images.githubusercontent.com/1855931/27068455-36842e6e-4fde-11e7-80d4-a8762fd3bcb6.png)  | ![flow0](https://user-images.githubusercontent.com/1855931/27068513-82627bba-4fde-11e7-994a-dde824e56a1e.png) |

I then augment only with an x,y translation. I'm using the same uniform_bernoulli / gaussian_bernoulli distribution options as in the models for FlowNetS.

| Image 0  | Image 1 | Flow |
| ------------- | ------------- | ------------- |
| ![img0_aug](https://user-images.githubusercontent.com/1855931/27068690-3db6080a-4fdf-11e7-90aa-6406d0b76765.png)  |  ![img1_aug](https://user-images.githubusercontent.com/1855931/27068695-3f805ec4-4fdf-11e7-90d6-2a279cb63b95.png) | ![flow_aug](https://user-images.githubusercontent.com/1855931/27068764-a00d0940-4fdf-11e7-9ed9-5a828be59050.png)  |

This seems like a large amount of information lost from such a huge translation. Half of the flow field is gone. Is this size of augmentation normal? As an extreme, sometimes I end up with an empty, noisy image after all of the transformations.

<img width="497" alt="screenshot 2017-06-13 02 29 32" src="https://user-images.githubusercontent.com/1855931/27068895-4ff34446-4fe0-11e7-9992-9343661f91f0.png">

Thanks for your help!

Sam

**Comment by nikolausmayer** [comment]
Hi Sam,

you're bound to lose information with a shift augmentation, there's no way around that. However, the FlowNet trained on *crops*, not whole images. If you crop out a smaller region from both images, you can safely apply this geometric stuff without losing information in the visible part (of course it gets a little harder because the allowed augmentations depend on each input's crop settings).

Best,
 Nikolaus
