### ISSUE TITLE
make fail on tools/convert_imageset_and_disparity

### ISSUE THREAD

**Issue by plaovem** [lmb-freiburg/flownet2#31]
hi, I follow the step on this page, and when I run the command: make -j 5 all tools pycaffe, I get the following errors:
NVCC src/caffe/layers/correlation_layer1d.cu
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
CXX tools/convert_imageset_and_disparity.cpp
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
CXX tools/test_net.cpp
tools/convert_imageset_and_disparity.cpp:5:1: warning: multi-line comment [-Wcomment]
 //   convert_imageset [-g] ROOTFOLDER/ LISTFILE DB_NAME RANDOM_SHUFFLE[0 or 1] \
 ^
In file included from ./include/thirdparty/CImg/CImg.h:208:0,
                 from tools/convert_imageset_and_disparity.cpp:39:
tools/convert_imageset_and_disparity.cpp: In function ‘int main(int, char**)’:
tools/convert_imageset_and_disparity.cpp:329:14: error: expected unqualified-id before ‘int’
     leveldb::Status status = leveldb::DB::Open(
              ^
In file included from tools/convert_imageset_and_disparity.cpp:17:0:
tools/convert_imageset_and_disparity.cpp:331:11: error: ‘status’ was not declared in this scope
     CHECK(status.ok()) << "Failed to open leveldb " << argv[arg_offset+2];
           ^
tools/convert_imageset_and_disparity.cpp:331:11: note: suggested alternatives:
In file included from /usr/include/boost/filesystem.hpp:17:0,
                 from ./include/caffe/util/io.hpp:4,
                 from tools/convert_imageset_and_disparity.cpp:37:
/usr/include/boost/filesystem/operations.hpp:396:15: note:   ‘boost::filesystem::status’
   file_status status(const path& p, system::error_code& ec)
               ^
/usr/include/boost/filesystem/operations.hpp:320:17: note:   ‘boost::filesystem::detail::status’
     file_status status(const path&p, system::error_code* ec=0);
                 ^
Makefile:582: recipe for target '.build_release/tools/convert_imageset_and_disparity.o' failed
make: *** [.build_release/tools/convert_imageset_and_disparity.o] Error 1
make: *** Waiting for unfinished jobs....
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
./include/caffe/parallel.hpp(99): warning: type qualifier on return type is meaningless

./include/caffe/parallel.hpp(99): warning: type qualifier on return type is meaningless

./include/caffe/parallel.hpp(99): warning: type qualifier on return type is meaningless

./include/caffe/parallel.hpp(99): warning: type qualifier on return type is meaningless

./include/caffe/parallel.hpp(99): warning: type qualifier on return type is meaningless

./include/caffe/parallel.hpp(99): warning: type qualifier on return type is meaningless

./include/caffe/parallel.hpp(99): warning: type qualifier on return type is meaningless

./include/caffe/parallel.hpp(99): warning: type qualifier on return type is meaningless

Could you help me to solve it, please? Thank you

**Comment by nikolausmayer** [comment]
Please check https://github.com/lmb-freiburg/flownet2/issues/26, might be the same `protobuf` issue.

**Comment by plaovem** [comment]
Sorry to reply lately. I just solve this problem. It is caused by opencv version. The opencv version should be 2, not 3. Then, this problem is solved.

**Comment by nikolausmayer** [comment]
Good to know, thanks ;)

**Comment by strivejin** [comment]
I have install opencv2.4.13 and uninstall opencv3.1 .when I type 'pkg-config --modversion opencv' then show 2.4.13. And I change the  ' OPENCV_VERSION := 2.4.13'  in Makefile.config. but when I run the command: make -j 5 all tools pycaffe, I get the following errors ： just like you

CXX tools/caffe.cpp
CXX tools/net_speed_benchmark.cpp
tools/convert_imageset_and_disparity.cpp:5:1: warning: multi-line comment [-Wcomment]
 //   convert_imageset [-g] ROOTFOLDER/ LISTFILE DB_NAME RANDOM_SHUFFLE[0 or 1] \
 ^
In file included from ./include/thirdparty/CImg/CImg.h:208:0,
                 from tools/convert_imageset_and_disparity.cpp:39:
tools/convert_imageset_and_disparity.cpp: In function ‘int main(int, char**)’:
tools/convert_imageset_and_disparity.cpp:329:14: error: expected unqualified-id before ‘int’
     leveldb::Status status = leveldb::DB::Open(
              ^
In file included from tools/convert_imageset_and_disparity.cpp:17:0:
tools/convert_imageset_and_disparity.cpp:331:11: error: ‘status’ was not declared in this scope
     CHECK(status.ok()) << "Failed to open leveldb " << argv[arg_offset+2];
           ^
tools/convert_imageset_and_disparity.cpp:331:11: note: suggested alternatives:
In file included from /usr/include/boost/filesystem.hpp:17:0,
                 from ./include/caffe/util/io.hpp:4,
                 from tools/convert_imageset_and_disparity.cpp:37:
/usr/include/boost/filesystem/operations.hpp:396:15: note:   ‘boost::filesystem::status’
   file_status status(const path& p, system::error_code& ec)
               ^
/usr/include/boost/filesystem/operations.hpp:320:17: note:   ‘boost::filesystem::detail::status’
     file_status status(const path&p, system::error_code* ec=0);
                 ^
Makefile:585: recipe for target '.build_release/tools/convert_imageset_and_disparity.o' failed
make: *** [.build_release/tools/convert_imageset_and_disparity.o] Error 1
make: *** Waiting for unfinished jobs....

Could you help me , please? Thank you

@plaovem 

@nikolausmayer

**Comment by nikolausmayer** [comment]
@strivejin 
What's your compiler version?
What's your LevelDB version? (`apt-cache policy libleveldb-dev`)
Please post the output of `VERBOSE=1 make tools` so we see what the compiler gets to work with.

**Comment by strivejin** [comment]
Ubuntu16.04 ； CUDA8 ； CUDNN5.1 ；opencv2.4.13; gcc version 5.3.0 (GCC)；

when I type 'apt-cache policy libleveldb-dev' I get:

libleveldb-dev:
  Installed: 1.18-5
  Candidate: 1.18-5
  Version table:
 *** 1.18-5 500
        500 http://mirrors.aliyun.com/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status

when I type 'VERBOSE=1 make tools' I get:

CXX .build_release/src/caffe/proto/caffe.pb.cc
LD -o .build_release/lib/libcaffe.so.1.0.0
CXX/LD -o .build_release/tools/test_net.bin
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
CXX tools/convert_imageset_and_disparity.cpp
tools/convert_imageset_and_disparity.cpp:5:1: warning: multi-line comment [-Wcomment]
 //   convert_imageset [-g] ROOTFOLDER/ LISTFILE DB_NAME RANDOM_SHUFFLE[0 or 1] \
 ^
In file included from ./include/thirdparty/CImg/CImg.h:208:0,
                 from tools/convert_imageset_and_disparity.cpp:39:
tools/convert_imageset_and_disparity.cpp: In function ‘int main(int, char**)’:
tools/convert_imageset_and_disparity.cpp:329:14: error: expected unqualified-id before ‘int’
     leveldb::Status status = leveldb::DB::Open(
              ^
In file included from tools/convert_imageset_and_disparity.cpp:17:0:
tools/convert_imageset_and_disparity.cpp:331:11: error: ‘status’ was not declared in this scope
     CHECK(status.ok()) << "Failed to open leveldb " << argv[arg_offset+2];
           ^
tools/convert_imageset_and_disparity.cpp:331:11: note: suggested alternatives:
In file included from /usr/include/boost/filesystem.hpp:17:0,
                 from ./include/caffe/util/io.hpp:4,
                 from tools/convert_imageset_and_disparity.cpp:37:
/usr/include/boost/filesystem/operations.hpp:396:15: note:   ‘boost::filesystem::status’
   file_status status(const path& p, system::error_code& ec)
               ^
/usr/include/boost/filesystem/operations.hpp:320:17: note:   ‘boost::filesystem::detail::status’
     file_status status(const path&p, system::error_code* ec=0);
                 ^
Makefile:585: recipe for target '.build_release/tools/convert_imageset_and_disparity.o' failed
make: *** [.build_release/tools/convert_imageset_and_disparity.o] Error 1

@nikolausmayer 

could you help me , thank you.

**Comment by strivejin** [comment]
when I 'make clean' then 'VERBOSE=1 make tools' I get this:

victorzhou@victorzhou-System-Product-Name:~/Documents/flownet2-master$ make clean 
victorzhou@victorzhou-System-Product-Name:~/Documents/flownet2-master$ VERBOSE=1 make tools
CXX tools/test_net.cpp
In file included from ./include/caffe/util/device_alternate.hpp:40:0,
                 from ./include/caffe/common.hpp:19,
                 from ./include/caffe/blob.hpp:8,
                 from ./include/caffe/caffe.hpp:7,
                 from tools/test_net.cpp:1:
./include/caffe/util/cudnn.hpp:8:34: fatal error: caffe/proto/caffe.pb.h: No such file or directory
compilation terminated.
Makefile:585: recipe for target '.build_release/tools/test_net.o' failed
make: *** [.build_release/tools/test_net.o] Error 1

@nikolausmayer

**Comment by nikolausmayer** [comment]
Your last error happens because `make clean` removes stuff which `make tools` needs but does not generate. You need another round of `make all`.

About your earlier error: I'm confused that the verbose `make` output does not include the actual compile command, something like:
`g++ tools/convert_imageset_and_disparity.cpp -MMD -MP -pthread -fPIC -DCAFFE_VERSION=1.0.0-rc3  -DNDEBUG -O2 -DUSE_CUDNN -DUSE_OPENCV -DUSE_LEVELDB -DUSE_LMDB -Dcimg_display=0 -DWITH_PYTHON_LAYER -IUDA_DIR/include -I/usr/include/hdf5/serial -I/usr/include/python2.7 -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/local/include -I.build_release/src -I./src -I./include -I/usr/local/cuda-8.0/include -Wall -Wno-sign-compare -c -o .build_release/tools/convert_imageset_and_disparity.o`

Can you add the following line to `tools/tools/convert_imageset_and_disparity.cpp` and try again?
`#include <leveldb/status.h>`

**Comment by strivejin** [comment]
could you tell me  what's your compiler version ？ and how can you get 'actual compile command' just like you?
 And it still don't work by adding #include <leveldb/status.h>. In addition I have Caffe in my home path ，and I can make it .Should I delete the Caffe folder ？

when I input ：gcc -v, I get this ：
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-unknown-linux-gnu/5.3.0/lto-wrapper
Target: x86_64-unknown-linux-gnu
Configured with: ../configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
Thread model: posix
gcc version 5.3.0 (GCC) 

I have gcc-4.8 in my computer ,and when I type ：gcc-4.8 -v, I get this:

Using built-in specs.
COLLECT_GCC=gcc-4.8
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.5-4ubuntu2' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.5 (Ubuntu 4.8.5-4ubuntu2) 

I add the #include <leveldb/status.h> to tools/tools/convert_imageset_and_disparity.cpp .but it still don't work. when I run the command:VERBOSE=1 make tools ,I get this:

LD -o .build_release/lib/libcaffe.so.1.0.0
CXX/LD -o .build_release/tools/test_net.bin
CXX tools/upgrade_net_proto_binary.cpp
CXX/LD -o .build_release/tools/upgrade_net_proto_binary.bin
CXX tools/convert_imageset_and_disparity.cpp
tools/convert_imageset_and_disparity.cpp:5:1: warning: multi-line comment [-Wcomment]
 //   convert_imageset [-g] ROOTFOLDER/ LISTFILE DB_NAME RANDOM_SHUFFLE[0 or 1] \
 ^
In file included from ./include/thirdparty/CImg/CImg.h:208:0,
                 from tools/convert_imageset_and_disparity.cpp:41:
tools/convert_imageset_and_disparity.cpp: In function ‘int main(int, char**)’:
tools/convert_imageset_and_disparity.cpp:331:14: error: expected unqualified-id before ‘int’
     leveldb::Status status = leveldb::DB::Open(
              ^
In file included from tools/convert_imageset_and_disparity.cpp:17:0:
tools/convert_imageset_and_disparity.cpp:333:11: error: ‘status’ was not declared in this scope
     CHECK(status.ok()) << "Failed to open leveldb " << argv[arg_offset+2];
           ^
tools/convert_imageset_and_disparity.cpp:333:11: note: suggested alternatives:
In file included from /usr/include/boost/filesystem.hpp:17:0,
                 from ./include/caffe/util/io.hpp:4,
                 from tools/convert_imageset_and_disparity.cpp:39:
/usr/include/boost/filesystem/operations.hpp:396:15: note:   ‘boost::filesystem::status’
   file_status status(const path& p, system::error_code& ec)
               ^
/usr/include/boost/filesystem/operations.hpp:320:17: note:   ‘boost::filesystem::detail::status’
     file_status status(const path&p, system::error_code* ec=0);
                 ^
Makefile:585: recipe for target '.build_release/tools/convert_imageset_and_disparity.o' failed
make: *** [.build_release/tools/convert_imageset_and_disparity.o] Error 1

**Comment by nikolausmayer** [comment]
My reference system is running `gcc version 5.4.0 20160609`.

Another Caffe installation on your system might cause problems. It's worth trying to isolate them, although your error does really look like it's caused by this.

It *looks* like a problem with LevelDB, but I have no experience in debugging this. The compiler does not complain about not finding the LevelDB headers, and your installation has the correct version. Do you have another LevelDB installation somewhere else on your machine?

**Comment by strivejin** [comment]
@nikolausmayer 

 Thank you for your reply. Could you tell me your Opencv version , and could you tell me which line you changed in your Makefile.config . Thank you very much .

**Comment by nikolausmayer** [comment]
I'm using the `Makefile.config` from our docker version: https://github.com/lmb-freiburg/flownet2-docker/blob/master/FN2_Makefile.config

The OpenCV version is 2.4.9

**Comment by xin527773783** [comment]
@strivejin  Are you fixed this problem?  just like you

**Comment by khurramHazen** [comment]
Were someone able to solve this problem? I facing the same issue and have tried by removing all leveldb installations and then reinstalling again from apt-get, but still having the same error.

**Comment by khurramHazen** [comment]
Finally I was able to (atleast) resolve the compilation error. Here are the changes that I made:

 1. changed `leveldb::Status status1 = leveldb::DB::Open(options, argv[arg_offset+2], &db1)` to `auto status1 = leveldb::DB::Open(options, argv[arg_offset+2], &db1)` Thanks @ZivS for pointing it out.
 2. changed Makefile from `LIBRARIES += glog gflags protobuf leveldb snappy \
  lmdb boost_system boost_filesystem hdf5_hl hdf5 m \
  opencv_core opencv_highgui opencv_imgproc opencv_imgcodecs opencv_videoio` to `LIBRARIES += glog gflags protobuf leveldb snappy \
  lmdb boost_system boost_filesystem hdf5_hl hdf5 m \
  opencv_core opencv_highgui opencv_imgproc opencv_imgcodecs opencv_videoio X11`
 3. Then changed the `#CUSTOM_CXX := g++` in Makefile.config to `CUSTOM_CXX := g++ -std=c++11` 

The code was able to compile. Will update once I load the LevelDB using the built object.
