### ISSUE TITLE
FlowNet2-ft-sintel model?

### ISSUE THREAD

**Issue by yxqlwl** [lmb-freiburg/flownet2#36]
Hi, 
    Is the FlowNet2-ft-sintel model available?
    Thanks~
Best,
ViJay

**Comment by eddy-ilg** [comment]
No, as far as I see one would only need it for the benchmark. Or is there another use for it?

Best, 

Eddy

**Comment by nikolausmayer** [comment]
Hi ViJay,

we have received a number of requests for the specialized finetuned models, and we have decided to publish them. Over the next ~week, we'll include them into the download script that comes with this repository, then close this issue. 

Best,
 Nikolaus

**Comment by nikolausmayer** [comment]
The download script now fetches our finetuned models for KITTI and Sintel.

Best,
 Nikolaus
