### ISSUE TITLE
FlowNet-CSS

### ISSUE THREAD

**Issue by sampepose** [lmb-freiburg/flownet2#38]
Hello,

I am confused about the training steps for your CSS model. 

A) You first train C and S separately. Then you use these results to construct CSS with the final S being randomly initialized. You fix the C and first S, and then train only the final S portion of the model.

B) You train C. Then take this result to make CS (with S random init), fix C, and train. You then take this result, add random init S (to make CSS), fix the first C and S, and train.

Which of the above is correct? Both are 3 trainings, but will yield different results.

Thank you,

Sam P

**Comment by nikolausmayer** [comment]
Hi Sam,
sorry for leaving this issue unattended for so long (I'm not sure why). In case you can still use an answer:

The second is correct. We always only train the last element of a stack, keeping all earlier elements fixed.
