### ISSUE TITLE
Thank you very much, Your code is very helpful to me. I have one question

### ISSUE THREAD

**Issue by parksungju** [lmb-freiburg/flownet2#44]
Hi. your flownet 2.0 code is best!!
but I'm wondering that this code can be used in windows
I'll try this code in windows. but I don't know how to de
please could you tell me whether can or not?
thank you very much!

**Comment by nikolausmayer** [comment]
Hi,

we have never tested whether our code runs on Windows. As far as I know, not even the stock Caffe might run just like that (but there's https://github.com/BVLC/caffe/tree/windows which seems to address this). So I'm sorry, but I don't know more about this than you... :)
