### ISSUE TITLE
why the result image in cs network more blur than result in c network?

### ISSUE THREAD

**Issue by Lvhhhh** [lmb-freiburg/flownet2#45]
the c network is trained in 40W iteration. and use the model to finetune the cs network .and after 20W iteration.  the result seems more blur than the result in c network .do you know where have the problem?

**Comment by nikolausmayer** [comment]
Hi,

are you talking about our pretrained models or about something which you trained yourself? What does "W" mean?
Could it be that the "s" part of the "cs" network is just not converged yet?

**Comment by Reeshark** [comment]
I think "W" which the quizzer mentioned means 10k(ten thousand) in Chinese saying. So the 40W means 400k. @nikolausmayer

**Comment by nikolausmayer** [comment]
@Reeshark Thanks. My best guess had been something like this, but Google would not tell me anything :)
@Lvhhhh did you solve the problem?

**Comment by Lvhhhh** [comment]
not yet . i give up the cs network now~
