### ISSUE TITLE
In run-flownet.py :  input_dict[net.inputs[blob_idx]] = input_data[blob_idx] IndexError: list index out of range

### ISSUE THREAD

**Issue by Mehuli-Ruh11** [lmb-freiburg/flownet2#46]
I am not able to figure out how to run the run-flownet.py and run-flownet-many.py. Could you please provide me an example ? The path for the net, I am using is /home/Downloads/flownet2-master/models/FlowNet2/. 
Also after running the following command in ubuntu terminal,
`$ python run-flownet.py /home/ruh/Downloads/flownet2-master/models/FlowNet2      /FlowNet2_weights.caffemodel.h5 \/home/ruh/Downloads/flownet2-master/models/FlowNet2/FlowNet2_deploy.prototxt.template \/home/ruh/Downloads/flownet2-master/data/FlyingChairs_examples/0000000-img0.ppm /home/ruh/Downloads/flownet2-master/data/FlyingChairs_examples/0000000-img1.ppm z.flo
`

It is giving me the following error

`<caffe._caffe.Net object at 0x7f0abe9cfe10>
Traceback (most recent call last):
  File "run-flownet.py", line 69, in <module>
    input_dict[net.inputs[blob_idx]] = input_data[blob_idx]
IndexError: list index out of range
`

**Comment by nikolausmayer** [comment]
Hi, did you resolve this issue?

**Comment by nikolausmayer** [comment]
Closed due to inactivity; if the problem persists, please reply and we will reopen the issue.
