### ISSUE TITLE
problem about "make-lmdbs.sh"

### ISSUE THREAD

**Issue by xugangtongji** [lmb-freiburg/flownet2#47]
hello,everyone.
I met some problems on making lmdbs. I have downloaded the ChairsSDHom and FlyingChairs dataset.
But after i run the make-lmdbs.sh, the realse file "data.mdb" didnt look right. It only 8KB. 
And the FlyingChairs.list can't be opened and its links are broken. I don't know how.
When I run the train program, it had errors.

**_“../../dispnet-release/data/FlyingChairs_release.list” doesn't exist

../build/tools/convert_imageset_and_flow.bin /media/xugang/data/data/FlyingChairs_release.list FlyingChairs_release_lmdb 0 lmdb_**

**Comment by xugangtongji** [comment]
how to creat a new FlyingChairs_release.list ?

**Comment by nikolausmayer** [comment]
fixed in d7ce9a3dffe63ce9d3497da1bc29b514af523d24

**Comment by nikolausmayer** [comment]
fixed in d7ce9a3dffe63ce9d3497da1bc29b514af523d24
