### ISSUE TITLE
question about principle of flownet

### ISSUE THREAD

**Issue by parksungju** [lmb-freiburg/flownet2#49]
Hi 
I have question about the part of the flownet
In corrleation layer, I want to know what "conv_redir" is and what the role of that is

**Comment by nikolausmayer** [comment]
Hi,
the correlation layer does not propagate much information about the content of the input images, it only does, well, correlation. To be able to use the actual image information, we do a normal convolution step (in parallel with the correlation layer) on the first image's blob, and then concat the result to the result from the correlation layer.
The `conv_redir` is the "redirected convolution" content of that parallel step.

**Comment by huangbiubiu** [comment]
And in Fig. 2 in the FlowNet paper, what's `sqrt` (next to the `conv_redir`) means?

**Comment by anksince89** [comment]
Hi, I have three doubts:
1. In the correlation layer, before the correlation of images, the depth was 256, but after correlation, the depth becomes 441. How is this happening? 
2. In the conv_redir part, are you taking only 16 filters and only for the first image?
3. What does "sqrt" mean in the figure?
Thank you. :)

**Comment by nikolausmayer** [comment]
1. The "441" has nothing to do with the "256". The correlation layer processes a 21x21 neighborhood (10 distance in each direction), that comes out as 21*21=441 channes.
2. conv_redir only processes the first image, yes. I don't know about the "16 filters" part.
3. "sqrt" hear means that a "square root" function is applied to this blob.

**Comment by agarwal-shubham** [comment]
Hi,
i have one small question regarding layer choice, why do we use conv_redir, I understand that as @nikolausmayer said we need input image information in addition to the correlation features, but if we use conv2a directly (without first passing through conv_redir) as input to conv3 layer (after concatenation with correlation features) will that not suffice. Also, we are just compressing the conv2a to fewer channels using conv_redir, is there any specific reason to do so.

**Comment by nikolausmayer** [comment]
@agarwal-shubham I cannot give an authoritative answer, but I believe that "just compressing the conv2a to fewer channels" was the main reason for adding "conv_redir" instead of a concatenation.
