### ISSUE TITLE
Reproducing Results FlowNet2

### ISSUE THREAD

**Issue by el3ment** [lmb-freiburg/flownet2#5]
If I wanted to reproduce your results (starting from random) do I need to manually train each network independently and load their respective weights in sequence, or is there a simpler method?

**Comment by nikolausmayer** [comment]
Hi Robert,

from scratch, getting to the full _FlowNet2_ entails 5 consecutive network setups (and more steps if you count finetuning). The _FlowNet2_ is a fusion (1 training) of a _FlowNet2-CSS-ft-sd_ (3 trainings, plus finetunings) and a _FlowNet2-SD_ (1 training). It's... not a quick process.

Best,
 Nikolaus

**Comment by el3ment** [comment]
Totally understand. We are porting the model to Tensorflow and want to make sure we have a version we can train from scratch. So when I run `caffe train --solver solver.prototxt` on the FlowNet2 model prototxt, is it loading the weights for the _FlowNet2-SD_ and _FlowNet2-CSS-ft-sd_ networks? As far as I can tell from the code is that it initializes all layers using MSRA and trains it end-to-end.

Robert

**Comment by eddy-ilg** [comment]
Yes, this would train it end to end (its provided for fine-tuning with ChairsSDHom). 

If you want to retrain the complete network stack, you have to do it step by step. We don't provide scripts for that.
