### ISSUE TITLE
DataAugmentationLayer error: shape mismatch

### ISSUE THREAD

**Issue by yaochx** [lmb-freiburg/flownet2#52]
when I run python code with two 640x480 images, it worked fine
`./scripts/run-flownet-many.py ./models/FlowNet2-css/FlowNet2-css_weights.caffemodel ./models/FlowNet2-css/FlowNet2-css_deploy.prototxt
`
However, I run the C++ code, the caffe code tell the following error:
> Cannot copy param 1 weights from layer 'img0s_aug'; shape mismatch.  Source param shape is 1 3 384 768 (884736); target param shape is 1 3 480 640 (921600). To learn this layer's parameters from scratch rather than copying from a saved net, rename the layer.

I found these comments which showed the possible reason?
> template <typename Dtype>
void DataAugmentationLayer<Dtype>::LayerSetUp(const vector<Blob<Dtype>*>& bottom,
      const vector<Blob<Dtype>*>& top)
> // TODO This won't work when applying a net to images of size different from what the net was trained on

It's very odd that python code worked, but c++ code did not work.
could you tell me the underlying? Thanks 
@eddy-ilg @nikolausmayer @mbuckler

**Comment by nikolausmayer** [comment]
Hi,
I'd guess the C++ code does some initialization step incorrectly. The augmentation layer should not perform geometry augmentation during testing.

**Comment by nikolausmayer** [comment]
Closing this issue due to no further replies. If the issue persists, please reply and we will reopen.
