### ISSUE TITLE
can i delete the Relu for the "deconv" when it concated to the "concat"

### ISSUE THREAD

**Issue by Lvhhhh** [lmb-freiburg/flownet2#54]
because i found that the values in "deconv" are majority negative. the Relu on them may decrease their power. can i delete the Relu of the "deconv" ?!

**Comment by nikolausmayer** [comment]
Considering that the networks are trained with that ReLU, I would tentatively assume that leaving it out leads to much worse results. But who knows? Try it and see what happens — it's science! :microscope:

**Comment by Lvhhhh** [comment]
i try . it seems have no effect.
