### ISSUE TITLE
How can I get the flow_x and flow_y (both grey picture)

### ISSUE THREAD

**Issue by ddnionio** [lmb-freiburg/flownet2#59]
Hi,
The flownet will generate the color flow file. But how can I get the flowx and flowy (2 grey pictures).
I may need them to feed another network, like temporal segment network.

Is there a standard way to do that?
Thanks

**Comment by nikolausmayer** [comment]
Hi,

the FlowNet does not produce a color image. The output is a .flo file in the Middlebury flow format. It directly stores the x and y flow channels. 
Google will provide links to code examples to parse this.

Best,
 Nikolaus

On August 31, 2017 10:44:07 AM GMT+02:00, ddnionio <notifications@github.com> wrote:
>Hi,
>The flownet will generate the color flow file. But how can I get the
>flowx and flowy (2 grey pictures).
>I may need them to feed another network, like temporal segment network.
>
>Is there a standard way to do that?
>Thanks
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/lmb-freiburg/flownet2/issues/59

-- 
==================================================
Nikolaus Mayer
University of Freiburg
Department of Computer Science
Computer Vision Group
Georges-Koehler-Allee, Building 052, Room 01-032
D-79110 Freiburg
Germany

Tel: +49-(0)761-203-8283
Email: mayern@informatik.uni-freiburg.de
==================================================

**Comment by ddnionio** [comment]
thanks!

**Comment by ddnionio** [comment]
hi @nikolausmayer 
I can get the flowx and flowy from the flo file now. But I met the problem when converting them into grey picture.
For grey picture, the value is between [0-255], and 128 means optical flow is 0
Do you know the max value and mix value for flowx[y] in flo format, so that I can scale it to [0,255]

**Comment by nikolausmayer** [comment]
There are no usable min/max values in FLO, that would not make sense. The format simply stores floating point values. I suggest you look at your problem again and find out what exactly you need, because I find it highly unlikely that you actually want "grey pictures".

Best,
 Nikolaus
