### ISSUE TITLE
About the usefulness of warping

### ISSUE THREAD

**Issue by ptriantd** [lmb-freiburg/flownet2#6]
First of all, great work!
I was wondering why warping is useful in this case. More specifically, what troubles me are the artifacts of the warping operation in the case of occlusions. Is there any guarantee that the warped image 2 we would get by using the ground truth flow is "closer" to image 1 than the warped image 2 we get by using the estimated flow in this case?

**Comment by eddy-ilg** [comment]
We fill occluded areas with 0s (black). In general the warping is useful to make a step towards the solution (or assessing the quality of the current solution). Compare e.g. the non-liner iteration in LDOF. 

I do not see a case when warping with ground truth could be worse than warping with the prediction.

**Comment by ptriantd** [comment]
Is this filling with 0s performed somewhere in this code?
