### ISSUE TITLE
ERROR on Compiling caffe

### ISSUE THREAD

**Issue by letatanu** [lmb-freiburg/flownet2#61]
I'm using 
Cuda: 8.0.61
Cudnn: 7.0 
Ubuntu 16.04
When I compiled Caffe with Cudnn:=1, I got this error:

 /usr/include/opencv2/gpu/gpu.hpp(432): error: vector is not a template

/usr/include/opencv2/gpu/gpu.hpp(438): error: vector is not a template

/usr/include/opencv2/gpu/gpu.hpp(1265): error: vector is not a template

Any idea? Thank you.

**Comment by nikolausmayer** [comment]
does this issue describe/solve your problem? https://github.com/liruoteng/FlowNet/issues/11

**Comment by letatanu** [comment]
I don't know if it is solved. I re-downloaded and compiled this project, this problem didn't show anymore.
