### ISSUE TITLE
Using FlowNet2.0 on Windows with Unity

### ISSUE THREAD

**Issue by Maryada-27** [lmb-freiburg/flownet2#62]
Hi,

I want to use FlowNet toolbox in windows. Is it possible to compile it on windows. I am facing lots of issues  while doing the same

**Comment by nikolausmayer** [comment]
Hi,

we do not have a Windows version of FlowNet2. The underlying Caffe framework has a branch for Windows (https://github.com/BVLC/caffe/tree/windows), but we have no experience with this and cannot provide support for it.

You might be able to use docker. Docker has a windows version (https://docs.docker.com/docker-for-windows/) and we have a FlowNet2 image (https://github.com/lmb-freiburg/flownet2-docker). 

Best,
 Nikolaus
