### ISSUE TITLE
problem about run-flownet.py

### ISSUE THREAD

**Issue by wangzhenglai** [lmb-freiburg/flownet2#65]
I am not able to run the run-flownet.py,could you please provide me an example ?
After running the following command in ubuntu terminal,
$ python run-flownet.py /media/root/F67EFD9D7EFD56B9/flownet/flownet2-master/models/FlowNet2/FlowNet2_weights.caffemodel.h5  \  /media/root/F67EFD9D7EFD56B9/flownet/flownet2-master/models/FlowNet2/FlowNet2_deploy.prototxt.template \ /media/root/F67EFD9D7EFD56B9/flownet/flownet2-master/data/FlyingChairs_examples/0000000-img0.ppm /media/root/F67EFD9D7EFD56B9/flownet/flownet2-master/data/FlyingChairs_examples/0000000-img1.ppm   z.flo
It is giving me the following error
run-flownet.py: error: unrecognized arguments: z.flo

**Comment by nikolausmayer** [comment]
Are the backslashes (`\`)really in your command, or is that an artifact of copy-paste?

**Comment by wangzhenglai** [comment]
thanks,I solve this issue with your advice.But I meet new issues....
After running command,It is giving me the following error:
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 40:22: Message type "caffe.LayerParameter" has no field named "augmentation_param".
F0918 14:29:10.478540  8157 upgrade_proto.cpp:79] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: /tmp/tmp2e_MMP
*** Check failure stack trace: ***

And another one,a new issue with convert_imageset_and_flow.bin when using make-lmdbs.sh
bash: ../build/tools/convert_imageset_and_flow.bin: Permission denied

I try  chmod 777 make-lmdbs.sh and chmod 777 convert_imageset_and_flow.bin ,but useless,can you help me?

**Comment by wangzhenglai** [comment]
I tried the following command again but useless for the first issue like others did: 
source  set-env.sh

**Comment by nikolausmayer** [comment]
I don't know about your "Permission denied" problem. It sounds like the compilation was not done correctly, or by a different user, or the files are on a filesystem which does not support execution or something like that.

Your first error still sounds like you have a mismatch between the Caffe version you use for compilation and the one you use at runtime: Your runtime Caffe used a `caffe.proto` file in which the `augmentation_param` is not defined. But we know it's defined in ours, so there must be a discrepancy on your side...

**Comment by letatanu** [comment]
@wangzhenglai You must use Caffe going with this project to avoid your first error. I used to use the original Caffe and there were some errors like that.

**Comment by nikolausmayer** [comment]
@letatanu Yes, that's what I meant in the last paragraph -- it seems to be a common issue. All the more reason to use our Docker image ;)

**Comment by nikolausmayer** [comment]
@wangzhenglai Is this issue still relevant, or can it be closed?

**Comment by wangzhenglai** [comment]
@nikolausmayer ,ok,you can close it. I solve it ,there are several caffe in my computer ,I forget to set correct caffe path for python .
