### ISSUE TITLE
Processing the ChairsSDHom dataset

### ISSUE THREAD

**Issue by el3ment** [lmb-freiburg/flownet2#7]
This isn't really an issue, but a note for the future.

After downloading the dataset you'll need to process the PFM files into FLO files, and then create .list files for the database loader. The following GISTs may be handy for you:

Create FLO files for all PFM files in a directory:
https://gist.github.com/el3ment/8f22539ad1770423771bf376ddafde58

Create .list files:
https://gist.github.com/el3ment/3720bc1002090f851840ac62a82d43ea

**Comment by Lvhhhh** [comment]
thank u!

**Comment by nikolausmayer** [comment]
@el3ment it seems that the PFM->FLO script does not correcly implement the PFM standard. The standard specifies that the image rows are stored **bottom to top**, i.e. for the conversion to be successful, the image must be mirrored vertically before exporting as FLO.

Best,
 Nikolaus
