### ISSUE TITLE
Visualizing optical flow files.

### ISSUE THREAD

**Issue by letatanu** [lmb-freiburg/flownet2#71]
Hi, I generate successfully the optical flow files from my video by Flownet2. However, when I use code gave by http://vision.middlebury.edu to visualize optical flow file, the code cannot read optical flow file. I also use another code to read the optical flow files, still get error in reading files. I wonder if the optical flow files generated from Flownet2 have the same structure as other optical flow files. Thank you.

**Comment by Maryada-27** [comment]
Hey,

Could you please tell me how did you calculate it for a video file. I am stuck to use it for a mp4/avi file

**Comment by nikolausmayer** [comment]
@letatanu The FlowNet2 generates FLO files. The code you link to should be able to read it. What error are you getting?

@Maryada-27 We do not support video files directly, but you can convert the video into individual frames (e.g. using ffmpeg: `ffmpeg -i your_video.avi -f image2 frame_%05d.png`). Then you can feed those frames into the FlowNet via the "run_flownet_many" script.

**Comment by nikolausmayer** [comment]
@letatanu @Maryada-27 Is this issue still relevant, or can it be closed?

**Comment by Maryada-27** [comment]
Yes please...
Thanks a lot

**Comment by letatanu** [comment]
@nikolausmayer It's my code error. Now I'm able to read FLO files. Thank you so much.

**Comment by AIaesthetic** [comment]
@nikolausmayer I managed to create .flo list and I can visualize each .flo file thanks to  http://vision.middlebury.edu/ . But I'm aiming to visualize the whole .flo list not just each individual .flo file. anyhelp? 
Thanks in advance
