### ISSUE TITLE
performance of Flownet2 is not good as the examples

### ISSUE THREAD

**Issue by minnieyao** [lmb-freiburg/flownet2#77]
Hi,
I am trying to use the Flownet2. I installed it and I run run-flownet.py /path/to/FlowNet2/FlowNet2t_weights.caffemodel.h5 \
                 /path/to/$net/$net_deploy.prototxt.template \ 
                 x.png y.png z.flo using the example images in flownet2/data/FlyingChairs_examples and then I got the error Layer conv1 has unknown engine
after that I replace the  "engine: CUDNN" by "engine: CAFFE" in prototxt files to fix this problem.
Then I used FlowNet2 on the example images got the .flo file. I compare it with the results in example files. My results is much bluring and cannot see chair in the output.
Could you help me figure out this problem? or I missed some necessary preprocess?

**Comment by nikolausmayer** [comment]
Hi,

the "FlowNet2" model's output and the groundtruth for the example pair (0000000-img0.ppm, 0000000-img1.ppm) are:

![flow](https://user-images.githubusercontent.com/7045923/32098139-09e06ad2-bb0c-11e7-95db-c716c49461cd.png)
![gt](https://user-images.githubusercontent.com/7045923/32098148-1168dc58-bb0c-11e7-90e6-ba6514a34389.png)

Sure the output is not as good as the groundtruth, but the chairs are recognizable. Do you get a much worse result?

**Comment by minnieyao** [comment]
Hi,

Thanks you for the reply. I tried more times and now I can get more robust results. I still have another question. Actually the  output is 3-D matrix and 2 channels in the 3rd dimension. The 2 images along the 3rd dimension are similar to the first input image and the intensity value are different from each other. How can I understand this two images attached?

Thank you !

Best,
Jingyao

**Comment by nikolausmayer** [comment]
I'm not sure I understand what you mean. The images I attached are just visualizations of the estimated and the groundtruth optical flow.

**Comment by minnieyao** [comment]
Hi

My question is based on the result file .flo. For example, the put image size is 370*370 then the output z.flo file size is 370*370*2. How can I understand this output file, two 370*370 images. Please see the attached images.  The legend is as follow:

Output[:,:,0]    0000000-img0.ppm

Output[:,:,1]    0000000-img1.ppm

Best,
Jingyao

**Comment by nikolausmayer** [comment]
Ah, I see. The first layer of the network output contains the x-component (the "horizontal") of the optical flow, and the second layer contains the y-component ("vertical").

The flow vector for a pixel (x,y) is (Output[x,y,0], Output[x,y,1]).

**Comment by minnieyao** [comment]
Thank you for the reply. May I have  one more question? How can I plot the optical  flow using *.flo  and get the results  which have the same color coding as you shown before?

**Comment by nikolausmayer** [comment]
The Middlebury group has a code package for flow visualization: http://vision.middlebury.edu/flow/code/flow-code.zip or http://vision.middlebury.edu/flow/code/flow-code-matlab.zip

I'm not sure if that gives you the coding I used. My examples might not even be real flow visualizations, I just wanted to show that the object boundaries are indeed visible.

**Comment by minnieyao** [comment]
I see, Thank you!

**Comment by nikolausmayer** [comment]
@PkuRainBow I'm getting good outputs for all those networks. Did you use our scripts to get these outputs?

**Comment by PkuRainBow** [comment]
All the models are pre-trained by you. It seems very strange.
