### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by DexterDinny** [lmb-freiburg/flownet2#78]
Encounter the following error during the compiling, how can I fix it?

CXX src/caffe/layers/hdf5_data_layer.cpp
src/caffe/layers/hdf5_data_layer.cpp:13:18: fatal error: hdf5.h: No such file or directory
compilation terminated.
Makefile:576: recipe for target '.build_release/src/caffe/layers/hdf5_data_layer.o' failed
make: *** [.build_release/src/caffe/layers/hdf5_data_layer.o] Error 1

**Comment by nikolausmayer** [comment]
- Do you have the `libhdf5-dev` package?
- Does `locate hdf5.h` list any location for a `hdf5.h` file?

**Comment by nikolausmayer** [comment]
@DexterDinny Is this issue still relevant? Or can it be closed?

**Comment by nikolausmayer** [comment]
(closed due to inactivity; reply to reopen if the issue persists)

**Comment by abhi-kumar** [comment]
Once libhdf5-dev is installed. Add the lines mentioned below in Makefile after line number 400:

INCLUDE_DIRS += $(PYTHON_INCLUDE) /usr/local/include /usr/include/hdf5/serial/ and
LIBRARY_DIRS += $(PYTHON_LIB) /usr/local/lib /usr/lib /usr/lib/x86_64-linux-gnu/hdf5/serial/

Regards,
Abhishek

**Comment by priyank1574q** [comment]
@nikolausmayer I am facing the same issue.
Yes, I have the libhdf5-dev package installed but I am not able to locate and hdf5.h file.

**Comment by nikolausmayer** [comment]
@priyank1574q if `locate hdf5.h` does not report anything, your "locate" database might just be out of date. Try `find /usr -name hdf5.h`. If that does not work, try reinstalling the package.
