### ISSUE TITLE
DownsamplingLayer cannot do backward

### ISSUE THREAD

**Issue by el3ment** [lmb-freiburg/flownet2#8]
My log file gives me a bunch of lines like

`[net.cpp:218] Downsample5 needs backward computation.`

before halting and throwing the error

`[downsample_layer.cu:138] DownsamplingLayer cannot do backward.`

A similar issue was raised before on the flownet: https://github.com/liruoteng/FlowNet/issues/9, but it seems strange that I would need to modify `net.cpp` since you were training successfully. Have you seen this issue before?

**Comment by el3ment** [comment]
I should say, I got this error after running `caffe train` using any of the models with a Downsampling layer.

**Comment by eddy-ilg** [comment]
Hi Robert, this issue should have been fixed a few days ago. Try the latest version and let me know if the problem persists.

**Comment by el3ment** [comment]
looks like we were too quick on the draw in cloning the repo :)

it's training fine now after re-cloning! thanks!
