### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by nkhademi** [lmb-freiburg/flownet2#80]
I am trying to generate the lmdb files using the make-lmdbs script. However, I realized the following files are missing:

ChairsSDHom_release_TEST.list
ChairsSDHom_release_TRAIN.list
FlyingThings3D_release_TEST.list
FlyingThings3D_release_TRAIN.list

Would it be possible to add them to the repository?

**Comment by nikolausmayer** [comment]
Hi,
we don't have these files; our database is organized differently. You can setup your own `.list` files from the contents of the dataset downloads (https://lmb.informatik.uni-freiburg.de/resources/datasets/SceneFlowDatasets.en.html and https://lmb.informatik.uni-freiburg.de/resources/datasets/FlyingChairs.en.html).

**Comment by nkhademi** [comment]
Thanks for your reply! I created my own list.
