### ISSUE TITLE
How to keep the output .flo have the same resolution as input images? 

### ISSUE THREAD

**Issue by chuchienshu** [lmb-freiburg/flownet2#81]
I'm using tensorflow to reproduce flownet2. when I apply function resize() to the output .flo(produced by four times deconv layer like flownet1), it's outline will  blur.while deconvolution get worse overall output. So I wonder that which way you chose in flownet2? Thanks!

**Comment by nikolausmayer** [comment]
Hi,
in deploy mode we upsample the input images to the next multiples of 64; the network outputs are then downsampled to the original resolution. This way we avoid any upsampling blur.

**Comment by chuchienshu** [comment]
Thanks!师傅！
