### ISSUE TITLE
caffe.set_logging_disabled()

### ISSUE THREAD

**Issue by pandamax** [lmb-freiburg/flownet2#83]
something wrong about caffe happened when i run the run-flownet.py
and my running code in my terminal:

~/flownet2-master/scripts$ python run-flownet.py /home/hzb/flownet2-master/flownet-model/FlowNet2-KITTI/FlowNet2-KITTI_weights.caffemodel.h5 /home/hzb/flownet2-master/flownet-model/FlowNet2-KITTI/FlowNet2-KITTI_deploy.prototxt.template /home/hzb/flownet2-master/scripts/frame10.png /home/hzb/flownet2-master/scripts/frame11.png output.flo

Traceback (most recent call last):
  File "run-flownet.py", line 63, in <module>
    caffe.set_logging_disabled()
AttributeError: 'module' object has no attribute 'set_logging_disabled'

Is there anyone meet the same problem?help is needed indeed!

**Comment by nikolausmayer** [comment]
Do you have multiple Caffe installations, such that the `run-flownet.py` script might find the wrong `caffe` module?

**Comment by wangzhenglai** [comment]
OK，I have meet this problem.you can open run-flownet.py, and explain caffe.set_logging_disabled() by #. And then you can run it successly.

**Comment by pandamax** [comment]
I have solved this problem，already！thanks anyway～

**Comment by JanySunny** [comment]
Hi, I got the same problem. Could you tell me how to solve it? Thanks very much~

**Comment by yacaeh** [comment]
try this before you run 'run-flownet.py' 
`source set-env.sh `

**Comment by 905471023** [comment]
I try explain "caffe.set_logging_disabled() by #", but it doesn't work

**Comment by BluebirdStory** [comment]
I use the caffe version provided by BVLC instead of the author, and now I have the same problem. I just wonder does the caffe version leads to this problem? Thanks @nikolausmayer

**Comment by nikolausmayer** [comment]
@BluebirdStory that's possible, yes. The Caffe code in this repo is not compatible with BVLC stock versions.
