### ISSUE TITLE
Augmentation: Exceeded maximum tries in finding spatial coeffs

### ISSUE THREAD

**Issue by JackieZhangdx** [lmb-freiburg/flownet2#84]
Hi. 

I try to train flownet on Sintel dataset and modify the crop size parameter in augmentation layer.
In my training process, there are several warning :" augmentation_layer_base.cpp:166] Augmentation: Exceeded maximum tries in finding spatial coeffs." The warning comes  3~10/100 iter.

I'm wondering if the warning would influence the training results.

Tks a lot!

**Comment by nikolausmayer** [comment]
Hi,
that's normal. The parameter randomization in the augmentation layer can lead to invalid augmentation proposals. The layer will try a few times to find a valid augmentation, but there's a cutoff because searching for too long would slow down training.

**Comment by JackieZhangdx** [comment]
Truly grateful for your help.
