### ISSUE TITLE
Compiling error on OS X 10.12.6

### ISSUE THREAD

**Issue by qqqwey941008** [lmb-freiburg/flownet2#85]
I've followed the steps to install all the dependency, but I still can not compile. 
I can't find any problem similar to mine. 
Here is the full log generated by running command `make -j 5 all tools pycaffe > log.txt.`
[log.txt](https://github.com/lmb-freiburg/flownet2/files/1463448/log.txt)

**Comment by nikolausmayer** [comment]
Hi,
the error happens in `src/caffe/layers/black_augmentation_layer.cpp`, line 44. That code path is only used if you compile in CPU_ONLY mode, but we do not support this. You'll have to enable GPU support :)

**Comment by qqqwey941008** [comment]
Thanks, disabling CPU_ONLY does solve that problem.
