### ISSUE TITLE
Multi-gpu

### ISSUE THREAD

**Issue by youssefoumate** [lmb-freiburg/flownet2#87]
Hello,
I'm wondering if I can run "run-flownet.py" with multiple gpus ?

thank you

**Comment by nikolausmayer** [comment]
Hi,
the script takes a `--gpu` parameter, so I think you should be able to just run two instances of the script in two terminals at the same time (see https://github.com/lmb-freiburg/flownet2/blob/master/scripts/run-flownet.py#L18).
