### ISSUE TITLE
Problem about finetuning on FlyingThings3D with network “FlowNetS“

### ISSUE THREAD

**Issue by shidahu** [lmb-freiburg/flownet2#90]
Hi, I try to reproduce your experimetal results in Tabel 1 given in the paper. 

Step-1: I train FlowNetS with Solver-long using FlyingChairs train&test dataset, then I evaluate the trained model on Sintel train clean dataset, the EPE value is 4.28 which is close to 4.24 given in paper. 

step-2: I finetune the pre-trained model in step-1 with Solver-fine using FlyingThing3D train dataset (I used flow files in _into_future/left_ and the corresponding image pairs, totally 20151 trituples). However, the EPE value is 3.98 which is greater than 3.79 given in paper with a large margin.

So, is there any problem in my experiment? Should I use FlyingThing3D train&test dataset to finetune the model? When finetune the model, I set _batch_size_=4 with _crop_size_ 768x384 while the _batch_size_ in FlowNet2-S_train.prototxt.template is 8, whether I use correct parameters or not?

**Comment by nikolausmayer** [comment]
Hi,
step 1 sounds good. What is your specific training set for step 2? 20151 samples is not the entire training set, right?
Good question about the batchsize. I'm afraid I'm not sure about FlowNet2-S and how its batchsize depends on the data size... please contact Eddy Ilg about this (https://lmb.informatik.uni-freiburg.de/people/ilge/)!

**Comment by shidahu** [comment]
@nikolausmayer , I use FlyingThing3D train dataset (folder _into_future/left_) in step 2, it contains 22390 images, but the last image in each sub-folder cannot be used. Thus, we can only generate 20151 image pairs.
In the past few days, I run step 2 again. This time I use all FlyingThing3D dataset (totally 24048 samples) with _batch_size_=8, the EPE evaluated on _Sintel train clean_ dataset is 3.90, which is close to 3.79 given in the paper.

**Comment by nikolausmayer** [comment]
Ah yes, of course. I forgot and just counted the frames... sounds good!

**Comment by zmlshiwo** [comment]
@shidahu How do you generate train/test (folder into_future/left) list? Which script is used?

**Comment by shidahu** [comment]
@zmlshiwo I write a python script to scan the folder and generate train/test list.

**Comment by zmlshiwo** [comment]
@shidahu I try to generate the list, but failed. Could you send me your python script about generate flyingthings3D train/test list? Thank you. My email is "zmlshiwo@outlook.com"

**Comment by nikolausmayer** [comment]
(closed due to inactivity)

**Comment by zhanghaozhou** [comment]
@zmlshiwo 
Hi zmlshiwo,

I am also trying to reproduce the results in the paper. Since the script for evaluating the EPE is not provided, could you please tell me how you evaluated your models?

Thanks a lot!

Haozhou

**Comment by zhanghaozhou** [comment]
@shidahu 
Hi shidahu,
I am also trying to reproduce the results in the paper. Since the script for evaluating the EPE is not provided, could you please tell me how you evaluated your models?

Thanks a lot!

Haozhou
