### ISSUE TITLE
Questions about warping

### ISSUE THREAD

**Issue by lan1991** [lmb-freiburg/flownet2#91]
Hi, I am confused about the "FlowWarp" operation. In FlowNet2-CS, It seems that you are using estimated forward flow to directly warp the img1 using FlowWarp layer. Suppose the forward flow(img0 -> img1) is (u,v), let (x1,y1) denotes pixel coords in img0, and (x2,y2) denotes pixel coods in img1. It should have (x2,y2) = (x1+u ,y1+v). I think it doesn't make any sense calculating (x2+u,y2+v). Or did I misunderstand the meaning of FlowWarp operation?

**Comment by nikolausmayer** [comment]
Hi,

the FlowWarp layer does *backward* warping, so we do not compute (x2+u,y2+v). We compute warped_image(x1,y1) := img1(x1+u,y1+v).

**Comment by lan1991** [comment]
@nikolausmayer Now I get it. Thanks for answering!
