### ISSUE TITLE
Directly Using FlowNet2_weights.caffemodel.h5 without finetuning.But optical flow is blank.

### ISSUE THREAD

**Issue by shanYanGuan** [lmb-freiburg/flownet2#93]
I doubt that I didn't config caffe correctly.
1.make all -j8
2.make pycaffe
Lacking 'make tools -j8' will make difference with testing?
By the way, when I run'make tools ', " make: Nothing to be done for 'tools' "shows out.Although bin file doesn't exist.

**Comment by shanYanGuan** [comment]
I have tried figures in data/FlyingChairs_examples.Optical flow is still blank.

**Comment by nikolausmayer** [comment]
`make all` includes `tools`, so you don't actually have to build it separately. Our instructions are a bit, uhm, in need of optimization there... ;)

I think we need a bit more information. What commands did you run? What was the output? Which files were created? How do you display the flow files?

**Comment by shanYanGuan** [comment]
commond:
`python scripts/run-flownet.py models/flownet2-models/FlowNet2/FlowNet2_weights.caffemodel.h5 models/flownet2-models/FlowNet2/FlowNet2_deploy.prototxt.template 0000000-img0.ppm 0000000-img1.ppm 111.flo`

output:111.flo

diaplay flow files:
`import numpy as np
import sys, os
import cv2
import matplotlib.pyplot as plt
import glob
from PIL import Image

def readFlow(name):
    f = open(name, 'rb')
    header = f.read(4)
    if header.decode("utf-8") != 'PIEH':
        raise Exception('Flow file header does not contain PIEH')
    width = np.fromfile(f, np.int32, 1).squeeze()
    height = np.fromfile(f, np.int32, 1).squeeze()
    flow = np.fromfile(f, np.float32, width * height * 2).reshape((height, width, 2))
    return flow.astype(np.float32)



def show_flow(path, two_pic=False):
    flow = readFlow(path)
    h, w, _ = flow.shape
    hsv = np.zeros((h, w, 3), np.uint8)
    hsv[..., 2] = 255
    if two_pic:
        plt.figure()
        plt.subplot(211)
        plt.imshow(flow[:,:,0]*2, cmap='jet')
        plt.subplot(212)
        plt.imshow(flow[:,:,1]*2, cmap='jet')
    else:
        mag, ang = cv2.cartToPolar(flow[...,0], flow[...,1])
        hsv[...,0] = ang*180/np.pi/2
        hsv[...,1] = cv2.normalize(mag,None, 0, 255,cv2.NORM_MINMAX)
        bgr = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)
        plt.figure()
        plt.imshow(bgr[::2, ::2, :])
        print(bgr)
        plt.show()
        #cv2.imshow('flow', bgr[::2, ::2, :])
        #cv2.imwrite('test_flow.png', bgr)
        #cv2.waitKey(0)


def show_rgb(paths):

    rgbi = np.array(Image.open(paths[0]))
    rgbj = np.array(Image.open(paths[1]))

    plt.figure()
    plt.subplot('211')
    plt.imshow(rgbi)
    plt.subplot('212')
    plt.imshow(rgbj)

def visualize_dataset(flow_dir, rgb_dir):
    lists = glob.glob(flow_dir + '/*.flo')
    lists = sorted(lists)
    for flof in lists:
        rgbi = int(flof.split('/')[1].split('.')[0])
        rgbj = rgbi+1
        rgbpath = [rgb_dir+'/%s.png'%str(rgbi).zfill(5), rgb_dir+'/%s.png'%str(rgbj).zfill(5)]
        show_flow(flof)
        #show_rgb(paths=rgbpath)
        plt.show()


show_flow(path='111.flo')
`

**Comment by shanYanGuan** [comment]
[visualize_flo.py.zip](https://github.com/lmb-freiburg/flownet2/files/1513522/visualize_flo.py.zip)

**Comment by nikolausmayer** [comment]
I'm getting this output, so the network produces a result (I'm probably using a wrong color scheme). Does the network print an error message? Try the `--verbose` option!

![bildschirmfoto_2017-11-30_09-22-33](https://user-images.githubusercontent.com/7045923/33420777-25212fca-d5b0-11e7-84f0-4d11ac6211f1.png)

**Comment by shanYanGuan** [comment]
No error message.How to config --verbose?

2017-11-30 16:25 GMT+08:00 Nikolaus Mayer <notifications@github.com>:

**Comment by nikolausmayer** [comment]
`python scripts/run-flownet.py ` **--verbose** ` models/flownet2-models/FlowNet2/FlowNet2_weights.caffemodel.h5 models/flownet2-models/FlowNet2/FlowNet2_deploy.prototxt.template 0000000-img0.ppm 0000000-img1.ppm 111.flo`

**Comment by shanYanGuan** [comment]
Ummm....Still not work.Maybe it due to enviorment ?My friend have run it
correctly in server.
And I have another question about two stream CNN.How can I stack 5 optical
flow to one optical flow?Just average each dx and dy?

2017-11-30 17:02 GMT+08:00 Nikolaus Mayer <notifications@github.com>:

**Comment by nikolausmayer** [comment]
That sounds like a good starting point to investigate. Maybe check version differences of CUDA, CuDNN etc between your machine and that server? :)

I'm not sure what you mean. Wherever we have multiple network inputs, they are all separate input channels (so 10 channels for 5 flow fields, for example). Averaging flow fields channel-wisely is probably not a good idea as it breaks the correlation between x and y...

**Comment by nikolausmayer** [comment]
(closed due to inactivity)

**Comment by zhanghaozhou** [comment]
@mehameha998 
hi,

Did you solve this problem of blank flow? I got the same error. Thanks a lot for your help!!

Best regards,
Haozhou
