### ISSUE TITLE
Data Augmentation while training?

### ISSUE THREAD

**Issue by anuragranj** [lmb-freiburg/flownet2#94]
Where is the data augmentation module located that is used while training? I can see src/caffe/data_transformer.cpp which probably defines all the transformation functions. I was hoping if someone could point me to the part of the code where these augmentations are being applied before training. In particular, I wanted to get into details of what sort of augmentation/preprocessing is used before feeding the data to the training pipeline.
Thanks

**Comment by nikolausmayer** [comment]
Hi, look for files in "src/caffe/layers" whose names contain "augmentation". The code is split into modules that generate augmentation parameters (e.g. where to crop), modules, that augment images, and modules that augment flow groundtruth.

**Comment by anuragranj** [comment]
Thanks
