### ISSUE TITLE
About train on flyingthings 3D

### ISSUE THREAD

**Issue by zmlshiwo** [lmb-freiburg/flownet2#99]
Hi, I want to fine-tuning flownet2 model on flyingthings. Where is the script about creating train list? I want to use into_future/left optical flow .pfm for training. How can I generate the train list?

**Comment by nikolausmayer** [comment]
There is no script for this; the list file just contains paths to the samples you want to stuff into your database, so it's easy to create using shell commands or Python.

**Comment by nikolausmayer** [comment]
(closed due to inactivity)
